- strr-web/composables/useBcrosCanadaPost.ts
- strr-web/pages/form-test.vue
*Issue:*https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20973
*Description of changes:* Simple composable to be iterated on and used in the rest of the form development, along with basic form field test.
> CanadaPost composable for further iteration and integration to form flow

- strr-web/components/bcros/form-section/property/Form.vue
> adding fix for nickname

- strr-web/components/bcros/form-section/contact-information/ContactInfo.vue
- strr-web/components/bcros/form-section/contact-information/Form.vue
- strr-web/components/bcros/form-section/contact-information/MailingAddress.vue
- strr-web/components/bcros/form-section/property/Address.vue
- strr-web/components/bcros/form-section/property/Details.vue
- strr-web/components/bcros/form-section/property/Form.vue
- strr-web/components/bcros/form-section/property/ListingDetails.vue
- strr-web/composables/useBcrosCanadaPost.ts
- strr-web/pages/create-account.vue
- strr-web/stores/strr.ts
*Issue:* 
[21152](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/21152)
[20659](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20659)
[20824](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20824)
[21153](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/21153)
Fixes field highlighting on completed steps
> Fixing field highlighting on completed steps

- strr-api/src/strr_api/services/registration_service.py
> bugfix: fix exception when sbc user not yet created

- strr-web/components/bcros/form-section/principal-residence/Form.vue
- strr-web/composables/useFees.ts
- strr-web/pages/create-account.vue
- strr-web/utils/formStateToApi.ts
> Feedback from initial review

- strr-api/src/strr_api/enums/enum.py
- strr-api/src/strr_api/services/payment_service.py
- strr-api/tests/unit/services/test_pay.py
bugfix for checking invoice status
> fix auth for checking invoice status via pay api

- strr-web/components/bcros/form-section/contact-information/Form.vue
- strr-web/composables/useBcrosNavigate.ts
- strr-web/composables/useRegistrations.ts
- strr-web/interfaces/account-i.ts
- strr-web/pages/application-status.vue
- strr-web/pages/create-account-pre/[id].vue
> Adding fix for empty invoices

- strr-web/pages/application-status.vue
> fixing incorrect filter

- strr-web/components/bcros/form-section/review/Subsection.vue
- strr-web/composables/useBcrosNavigate.ts
- strr-web/lang/en.json
- strr-web/middleware/setupAuth.global.ts
- strr-web/pages/terms-of-service.vue
- strr-web/stores/strr.ts
[21766: Preferred name in review](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/21766)
[21938: PID validation](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/21938)
Adding PID validation to match format: 111-111-111
Adding preferred name to review page for primary and secondary contact
> PID validation & Preferred name

- strr-web/pages/application-status.vue
> removing pending for applied status

- strr-web/interfaces/account-i.ts
- strr-web/utils/formStateToApi.ts
> adding optional reason blocks

- strr-web/pages/application-details/[applicationId]/ltsa/index.vue
> adding array access for ltsa

- strr-api/src/strr_api/common/utils.py
- strr-api/src/strr_api/services/approval_service.py
- strr-api/tests/mocks/json/registration_use_sbc_account_ltsa.json
> changes to auto approval logic around address check

- strr-web/composables/useRegistrations.ts
- strr-web/interfaces/ltsa-data-i.ts
- strr-web/pages/application-details/[applicationId]/ltsa/index.vue
> fixing type

- strr-web/pages/application-details/[applicationId]/ltsa/index.vue
> adding data accessor

- strr-web/components/bcros/existing-accounts-list/ExistingAccountsList.vue
- strr-web/components/bcros/fee-widget/FeeWidget.vue
- strr-web/components/bcros/status-card/StatusCard.vue
- strr-web/composables/useBcrosAuth.ts
- strr-web/interfaces/property-type-map-i.ts
- strr-web/middleware/setupAuth.global.ts
- strr-web/pages/account-select.vue
- strr-web/pages/application-details/[applicationId]/index.vue
- strr-web/pages/create-account.vue
- strr-web/stores/keycloak.ts
- strr-web/utils/propertyTypeMap.ts
> Adding Account Select & fixing open in new tab

- strr-web/components/bcros/typography/H2.vue
- strr-web/pages/create-account-pre/[id].vue
- strr-web/pages/create-account.vue
- strr-web/pages/registry-dashboard.vue
Fixes mapping FE dropdown value to backend enum
> Fixing enum mapping logic

- strr-web/composables/useRegistrations.ts
> reverting endpoint call

- strr-web/utils/axios.ts
*Issue:*
- https://github.com/bcgov/entity/issues/22345
- Add Account-Id in HTTP request header
> Update headers to include Account-Id

- strr-web/components/bcros/fee-widget/FeeWidget.vue
- strr-web/components/bcros/status-card/StatusCard.vue
- strr-web/composables/useChipFlavour.ts
- strr-web/lang/en.json
- strr-web/pages/application-details/[applicationId]/index.vue
> Missed fixes found in testing

- strr-api/src/strr_api/enums/enum.py
- strr-api/src/strr_api/services/auth_service.py
- strr-api/src/strr_api/services/event_records_service.py
- strr-api/src/strr_api/services/payment_service.py
- strr-api/src/strr_api/services/registration_service.py
Copy changes for event records.
> update event records verbage

- strr-web/components/bcros/form-section/contact-information/ContactDetails.vue
- strr-web/components/bcros/form-section/contact-information/MailingAddress.vue
- strr-web/components/bcros/form-section/property/Address.vue
- strr-web/components/bcros/form-section/property/Details.vue
- strr-web/components/bcros/status-card/StatusCard.vue
- strr-web/lang/en.json
- strr-web/pages/application-details/[applicationId]/index.vue
- strr-web/pages/application-details/[applicationId]/ltsa/index.vue
- strr-web/pages/registry-dashboard.vue
- strr-web/stores/keycloak.ts
> Adding missed fixes from testing

- strr-web/pages/application-status.vue
> sprint review bug fix - adding application status chip logic

- strr-web/pages/registry-dashboard.vue
- strr-web/stores/strr.ts
*Issue:*
- https://github.com/bcgov/entity/issues/22401
- Remove upload documents from the payment flow
- Other small fixes
> Remove upload documents from payment flow

- Makefile
- README.md
- docker-compose.yml
- strr-web/Dockerfile
Issue:
- bcgov/entity#22528
Ensure environment variables are available for nuxt at build time in dev container
> Webui local dev - docker compose changes

- strr-web/components/bcros/banner/banner.vue
- strr-web/components/bcros/chip/Chip.vue
- strr-web/components/bcros/status-card/StatusCard.vue
- strr-web/components/bcros/stepper/StepperFooter.vue
- strr-web/layouts/wideGutters.vue
- strr-web/layouts/wideNoSpace.vue
- strr-web/package.json
- strr-web/pages/account-select.vue
- strr-web/pages/application-details/[applicationId]/index.vue
- strr-web/pages/application-status.vue
- strr-web/pages/create-account-pre/[id].vue
- strr-web/pages/create-account.vue
- strr-web/pages/listing-details/[listingId].vue
- strr-web/pages/success/[id].vue
- strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
*Issue:*
- bcgov/entity/issues/22484
- Add max-width layout and other small fixes
> Add 'max-width' for All Pages

- .github/workflows/e2e.yml
- .vscode/settings.json
*Issue:* 22356
- bcgov/entity/issues/22356
Fien tuning of the GitHub workflow for e2e script execution
> Tune parameters for the e2e test script

- strr-web/package.json
*Issue:*
- bcgov/entity/issues/22356
Add coverage to test:
"test": "vitest run --coverage && cp ./coverage/cobertura-coverage.xml ./coverage.xml",
> add coverage to the unit test

- .github/workflows/e2e.yml
*Issue:*
- bcgov/entity/issues/22356
Adding e2e parameters and saving videos, screenshots for debugging purposes.
> feat: extending the e2e test parameters

- .github/workflows/e2e.yml
*Issue:*
- bcgov/entity/issues/22356
Adding the HOST param due to dependency.
> fix: Add HOST to ENV params

- .sonarcloud.properties
*Issue:*
- bcgov/entity/issues/22360
Preparing for the sonarcloud integration.
> Prep for sonarcloud integration

- strr-web/.eslintrc.json
- strr-web/composables/useApplications.ts
- strr-web/composables/useBcrosCanadaPost.ts
- strr-web/interfaces/paginated-applications-i.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/application-status.vue
- strr-web/pages/registry-dashboard.vue
*Issue:*
- bcgov/entity/issues/22592
- Fix Examiner Dashboard
> Fix filter tabs on Examiner Dashboard

- strr-web/package.json
- strr-web/pages/create-account.vue
*Issue:*
- bcgov/entity/issues/22492
- Add scroll to top on Create Account steps
> Add scroll to top on Create Account steps

- strr-web/lang/en.json
- strr-web/pages/application-details/[id]/auto-approval/index.vue
- strr-web/pages/application-details/[id]/index.vue
*Issue:* https://github.com/bcgov/entity/issues/22583
https://github.com/bcgov/entity/issues/22594
Included fixes and match mobile Figma design for application details page.
> UI - Application Details Bug Fixes

- strr-web/components/FilingHistory.vue
- strr-web/composables/useApplications.ts
- strr-web/composables/useRegistrations.ts
- strr-web/interfaces/filing-history-event-i.ts
- strr-web/interfaces/registration-history-event-i.ts
- strr-web/package.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/registration-details/[id]/index.vue
*Issue:*
- Fix Filing History dates in Registration Details
> Fix Filing History dates in Registration Details

- strr-api/src/strr_api/responses/AutoApprovalResponse.py
- strr-api/src/strr_api/services/application_service.py
- strr-api/src/strr_api/services/approval_service.py
- strr-web/composables/useApplications.ts
- strr-web/composables/useRegistrations.ts
- strr-web/interfaces/auto-approval-data-i.ts
- strr-web/interfaces/ltsa-data-i.ts
- strr-web/package.json
- strr-web/pages/application-details/[id]/auto-approval/index.vue
- strr-web/pages/application-details/[id]/ltsa/index.vue
*Issue:* https://github.com/bcgov/entity/issues/22631
https://github.com/bcgov/entity/issues/22632
Application detail Auto Approval and LTSA pages are now working.
> UI - Support New Auto Approval Record and LTSA Endpoints

- strr-api/src/strr_api/resources/application.py
*Issue:* https://github.com/bcgov/entity/issues/22929
Removed `document_key` and now using `file_key`.
> Backend - Swagger Fix in Applications document endpoints

- strr-api/pyproject.toml
- strr-api/src/strr_api/responses/RegistrationResponse.py
- strr-api/src/strr_api/schemas/schemas/registration.json
*Issue:* https://github.com/bcgov/entity/issues/22961
Adds documents list to registration response.
> Backend - Documents list in Registration Response

- strr-web/composables/useApplications.ts
- strr-web/composables/useRegistrations.ts
- strr-web/interfaces/account-i.ts
- strr-web/interfaces/application-i.ts
- strr-web/interfaces/document-upload-i.ts
- strr-web/interfaces/registration-i.ts
- strr-web/package.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/registration-details/[id]/index.vue
*Issue:*
- bcgov/entity/issues/22318
- bcgov/entity/issues/22403
- Upload and Download Supporting Documents using new API endpoints for Applications and Registrations
> Upload and Download Supporting Documents

- strr-web/components/bcros/banner/banner.vue
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/application-details/[id]/ltsa/index.vue
- strr-web/pages/terms-of-service.vue
- strr-web/stores/keycloak.ts
*Issue:*
- bcgov/entity/issues/22593
- Update LTSA page as per the latest design
- Fix Terms of Service redirect issue by clearing out the session storage.
> Update LTSA page. Fix Terms of Service issue.

- strr-web/components/bcros/form-section/principal-residence/Form.vue
- strr-web/package.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/registration-details/[id]/index.vue
*Issue:*
- https://github.com/bcgov/entity/issues/22520
Make Document Name left aligned in Application and Registration Detail page.
> UI - Document Name Left Align

- strr-web/components/bcros/form-section/review/Form.vue
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/utils/common.ts
*Issue:*
- https://github.com/bcgov/entity/issues/22935
Display correct ownership type label in review and application detail.
> UI - Display Correct Ownership Type Label

- strr-web/pages/terms-of-service.vue
- strr-web/stores/account.ts
*Issue:*
- bcgov/entity/issues/23180
Changes to ```terms-of-service.vue``` and ```account.ts``` to account for TOS Changes.
> fix: Update UI Handling for new TOS API

- strr-web/pages/platform-application.vue
*Issue:*
- https://github.com/bcgov/entity/issues/22801
@dimak1 This implements the `BcrosStepperFooter` for platform-application
> UI - Platform Application Footer

- strr-api/migrations/versions/20240908_0710_7a9f3c2e8b5d_.py
- strr-api/poetry.lock
- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/responses/AutoApprovalRecordResponse.py
- strr-api/src/strr_api/responses/LTSARecordResponse.py
- strr-api/src/strr_api/services/application_service.py
- strr-api/tests/unit/resources/test_registration_applications.py
- strr-web/interfaces/application-i.ts
- strr-web/pages/registry-dashboard.vue
*Issue:*
- https://github.com/bcgov/entity/issues/22636
- https://github.com/bcgov/entity/issues/22897
Added `application_number` to application table, Added function in migration to add application_number to existing records.
> Add Application Number to application

- strr-web/app.config.ts
- strr-web/components/Breadcrumb.vue
- strr-web/composables/useBreadcrumb.ts
- strr-web/enums/route-name-e.ts
- strr-web/enums/route-names-e.ts
- strr-web/interfaces/breadcrumb-i.ts
- strr-web/lang/en.json
- strr-web/layouts/default.vue
- strr-web/layouts/wide.vue
- strr-web/layouts/wideNoSpace.vue
- strr-web/page-data/breadcrumbs.ts
- strr-web/pages/application-details/[id]/auto-approval/index.vue
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/application-details/[id]/ltsa/index.vue
- strr-web/pages/listing-details/[listingId].vue
- strr-web/pages/registration-details/[id]/index.vue
- strr-web/pages/success/[id].vue
- strr-web/stores/state/strr-state-model.ts
- strr-web/stores/store.ts
- strr-web/tailwind.config.ts
- strr-web/tests/app.spec.ts
*Issue:*
- bcgov/entity/issues/22557
- Add Breadcrumb across the application
- Do not show Breadcrumb on certain routes
> Add Breadcrumb Across the App

- strr-web/components/common/BcrosContactInfo.vue
- strr-web/components/common/InfoModal.vue
- strr-web/composables/useBreadcrumb.ts
- strr-web/lang/en.json
- strr-web/nuxt.config.ts
- strr-web/package.json
- strr-web/pages/account-select.vue
- strr-web/pages/application-status.vue
- strr-web/pages/create-account-pre/[id].vue
- strr-web/pages/finalization.vue
- strr-web/pages/listing-details/[listingId].vue
- strr-web/pages/success/[id].vue
- strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
- strr-web/tests/unit/components/BaseModal.spec.ts
*Issue:*
- bcgov/entity/issues/23018
- Initial setup for Info Modal
- Bcros Contact Info component
- Unit tests
- Cleanup
> Add Modal for Account Setup Help

- strr-web/components/bcros/banner/banner.vue
- strr-web/composables/useRegistrations.ts
- strr-web/package.json
- strr-web/pages/application-details/[id]/auto-approval/index.vue
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/application-details/[id]/ltsa/index.vue
- strr-web/pages/registration-details/[id]/index.vue
*Issue:*
- bcgov/entity/issues/23389
- Update Issue Certificate Endpoint
> Update Issue Certificate Endpoint

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/services/application_service.py
- strr-api/tests/unit/resources/test_registration_applications.py
*Issue:*
- https://github.com/bcgov/entity/issues/23279
Security bug is fixed. The API behaviour [in terms of response codes] remains unchanged for now. Only the authorization check function needed updates.
> API - Bugfix - Host Application Access

- .github/CODEOWNERS
*Issue:*
*Description of changes: adding Lekshmi as a code owner*
> Add code owner for strr-api directory

- strr-web/lang/en.json
*Issue:*
- https://github.com/bcgov/entity/issues/23083
Fixed/corrected contact email
> UI - Change Contact Email Address

- strr-web/app.vue
- strr-web/components/common/LoadingIndicator.vue
- strr-web/composables/useBcrosAuth.ts
- strr-web/middleware/setupAuth.global.ts
- strr-web/nuxt.config.ts
- strr-web/package.json
- strr-web/pages/application-status.vue
- strr-web/pages/create-account.vue
- strr-web/pages/registry-dashboard.vue
- strr-web/pnpm-lock.yaml
- strr-web/stores/keycloak.ts
- strr-web/tests/app.spec.ts
- strr-web/tests/unit/composables/useBcrosAuth.spec.ts
*Issue:*
- bcgov/entity/issues/22518
- Add loading indicator when navigating between pages
- Optimize API calls by combining and calling them at once
- Add icons as a dependency (instead of dev dependency) - an attempt to solve issue when icons not loading
> Add Loading Indicator. Optimize API calls.

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/resources/application.py
- strr-api/src/strr_api/responses/AutoApprovalRecordResponse.py
- strr-api/src/strr_api/responses/LTSARecordResponse.py
- strr-api/src/strr_api/services/application_service.py
- strr-api/tests/postman/strr-api.postman_collection.json
- strr-api/tests/postman/strr-api.postman_environment.json
- strr-api/tests/unit/resources/test_registration_applications.py
- strr-api/tests/unit/resources/test_registrations.py
*Issue:*
- https://github.com/bcgov/entity/issues/23419
> Backend: Replace Application ID with Application Number

- .github/CODEOWNERS
- queue_services/strr-pay/src/strr_pay/config.py
> Testing valut config mapping

- strr-web/components/bcros/banner/banner.vue
- strr-web/composables/useRegistrations.ts
- strr-web/composables/useScreenSize.ts
- strr-web/enums/host-examiner-actions-e.ts
- strr-web/interfaces/application-i.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/application-details/[id]/auto-approval/index.vue
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/application-details/[id]/ltsa/index.vue
- strr-web/pages/registration-details/[id]/index.vue
- strr-web/pnpm-lock.yaml
- strr-web/tests/mocks/mockApplication.ts
- strr-web/tests/unit/components/banner/Banner.spec.ts
- strr-web/tests/unit/composables/useBcrosAuth.spec.ts
- strr-web/tests/unit/utils/helper-functions.ts
*Issue:*
- bcgov/entity/issues/22937
- Use `hostActions` and `examinerActions` returned by API to display action buttons in the Application
> Host and Examiner Actions in Application

- strr-api/src/strr_api/models/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/23532
This PR needs to merged to fully test https://github.com/bcgov/STRR/pull/183.
> Backend: Add isCertificateIssued to applicationHeader

- strr-api/.dockerignore
> TEST: update dockerignore

- strr-platform-web/app/assets/styles/layout.css
- strr-platform-web/app/components/connect/ButtonControl.vue
- strr-platform-web/app/components/connect/fee/Widget.vue
- strr-platform-web/app/components/modal/Base.vue
- strr-platform-web/app/composables/useStrrModals.ts
- strr-platform-web/app/enums/application-type.ts
- strr-platform-web/app/interfaces/connect-btn-control/item-i.ts
- strr-platform-web/app/interfaces/platform-application.ts
- strr-platform-web/app/layouts/connect-form.vue
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/plugins/strr-api.ts
- strr-platform-web/app/stores/platformApplication.ts
- strr-platform-web/app/utils/platform-application.ts
> UI - Platform: Form submission

- strr-web/package.json
- strr-web/utils/formStateToApi.ts
*Issue:*
- bcgov/entity/issues/23551
- Fix for Business Lic Exp Date submission
> Fix for Business Lic Exp Date submission

- strr-web/components/bcros/existing-accounts-list/ExistingAccountsList.vue
- strr-web/components/bcros/footer/Footer.vue
- strr-web/components/common/LoadingIndicator.vue
- strr-web/composables/useBcrosAuth.ts
- strr-web/composables/useBcrosNavigate.ts
- strr-web/composables/useRegistrations.ts
- strr-web/composables/useTermsOfService.ts
- strr-web/enums/route-names-e.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/account-select.vue
- strr-web/pages/application-status.vue
- strr-web/pages/create-account.vue
- strr-web/pages/terms-of-service.vue
- strr-web/stores/account.ts
- strr-web/tests/unit/components/footer/Footer.spec.ts
- strr-web/tests/unit/composables/useBcrosAuth.spec.ts
- strr-web/tests/unit/stores/account.spec.ts
- strr-web/utils/axios.ts
*Issue:*
- bcgov/entity/issues/23663
- Update Account Login / Create / Switch flow as per new requirements (see ticket)
- Update unit tests
> Update Account Flow

- strr-web/components/bcros/form-section/property/Details.vue
- strr-web/components/bcros/form-section/property/Form.vue
- strr-web/enums/host-residence-e.ts
- strr-web/enums/rental-unit-space-type-e.ts
- strr-web/interfaces/account-i.ts
- strr-web/lang/en.json
- strr-web/stores/strr.ts
- strr-web/utils/formStateToApi.ts
*Issue:*
- bcgov/entity/issues/23547
> 23547 rest of the property details

- strr-web/components/bcros/form-section/property-manager/ContactDetails.vue
- strr-web/components/bcros/form-section/property-manager/Form.vue
- strr-web/package.json
- strr-web/stores/strr.ts
*Issue:*
- https://github.com/bcgov/entity/issues/23751
@rstens 
> UI - Property Manager Fixes - From QA Testing

- strr-web/components/bcros/form-section/contact-information/ContactDetails.vue
- strr-web/components/bcros/form-section/property-manager/BusinessDetails.vue
- strr-web/components/bcros/form-section/property-manager/ContactDetails.vue
- strr-web/components/bcros/form-section/property-manager/ContactName.vue
- strr-web/components/bcros/form-section/property-manager/Form.vue
- strr-web/package.json
- strr-web/stores/strr.ts
- strr-web/tests/unit/components/form-section/property-manager/BusinessDetails.spec.ts
- strr-web/tests/unit/components/form-section/property-manager/BusinessMailingAddress.spec.ts
- strr-web/tests/unit/components/form-section/property-manager/ContactDetails.spec.ts
- strr-web/tests/unit/components/form-section/property-manager/ContactName.spec.ts
- strr-web/tests/unit/components/form-section/property-manager/Form.spec.ts
*Issue:*
- https://github.com/bcgov/entity/issues/23743
Fix this: https://github.com/bcgov/entity/issues/23743#issuecomment-2438878721
> UI - Validation Updates - QA Feedback

- strr-platform-web/package.json
> revert lint run over '/app' only

- strr-platform-web/app/components/connect/ButtonControl.vue
- strr-platform-web/app/components/connect/form/phoneNumber/CountryCode.vue
- strr-platform-web/app/components/connect/form/phoneNumber/Index.vue
- strr-platform-web/app/components/form/common/Contact.vue
- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/stores/platformApplication.ts
- fix phone input not unmasking value
- missing i18n translations for 'certify' and confirmation checkbox error messages
- add nameLocal as hidden text for screen readers to country code dropdown
- move button control buttons to right side per Scotts request
> Platform - UI: Minor UI updates

- strr-web/components/FilingHistory.vue
- strr-web/components/bcros/form-section/contact-information/Form.vue
- strr-web/components/bcros/form-section/property-manager/Form.vue
- strr-web/components/bcros/form-section/property-manager/SummaryView.vue
- strr-web/components/bcros/form-section/property/Details.vue
- strr-web/components/bcros/form-section/property/Form.vue
- strr-web/components/bcros/form-section/review/Form.vue
- strr-web/components/bcros/form-section/review/Subsection.vue
- strr-web/composables/useApplications.ts
- strr-web/interfaces/account-i.ts
- strr-web/interfaces/application-i.ts
- strr-web/interfaces/registration-i.ts
- strr-web/lang/en.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/create-account.vue
- strr-web/pages/finalization.vue
- strr-web/pages/registration-details/[id]/index.vue
- strr-web/stores/strr.ts
- strr-web/tests/mocks/mockApplication.ts
- strr-web/tests/mocks/mockPropertyManager.ts
- strr-web/tests/unit/components/form-section/property/Form.spec.ts
- strr-web/tests/unit/components/form-section/review/Subsection.spec.ts
- strr-web/tests/unit/pages/rental-application.spec.ts
- strr-web/tests/unit/utils/formStateToApi.spec.ts
- strr-web/utils/format-helper.ts
*Issue:*
- bcgov/entity/issues/23745
- bcgov/entity/issues/23746
- Add Property Manager section to Review page
- Add Property manager section to Application Details and Registration Details pages
- Add unit tests
- Small fixes and minor tech debt cleanup
> Property Manager - Review and Confirm, App & Reg Details pages

- strr-platform-web/app/components/connect/form/address/Index.vue
- strr-platform-web/app/components/connect/form/field/Group.vue
- strr-platform-web/app/components/connect/form/field/Index.vue
- strr-platform-web/app/components/connect/form/phoneNumber/CountryCode.vue
- strr-platform-web/app/components/connect/form/phoneNumber/Index.vue
- strr-platform-web/app/components/form/common/Contact.vue
- strr-platform-web/app/components/form/platform/BusinessDetails.vue
- strr-platform-web/app/components/form/platform/ContactInfo.vue
- strr-platform-web/app/components/form/platform/Details.vue
- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/utils/connect-validation/index.ts
- fix aria labels
- add aria-required, aria-invalid, aria-describedby and aria-disabled to relevant input fields
- update input types eg: text -> email/url/tel (need to muck with zod to change string to number for fax/extension) 
> Platform - UI: A11y Updates

- strr-platform-web/app/components/connect/SystemBanner.vue
- strr-platform-web/app/layouts/default.vue
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/middleware/1.enable-app.ts
- strr-platform-web/app/pages/comingSoon.vue
- strr-platform-web/nuxt.config.ts
- strr-platform-web/package.json
*Issue:*
- bcgov/entity/issues/24118
> Platform UI - ldflag stuff

- strr-platform-web/app/components/connect/form/phoneNumber/Index.vue
> Platform UI - phone number input bug fix

- strr-platform-web/app/components/connect/Stepper.vue
- strr-platform-web/app/components/form/common/Review/Row.vue
- strr-platform-web/app/components/form/common/Review/Section.vue
- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/app/composables/useStrrModals.ts
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/pages/platform/application.vue
*Issue:*
- bcgov/entity#24109
Stepper:
- stepper aria label
- make stepper an ordered list
- add 'Step x of x' to button aria label
- add aria-current step to button attrs
- stepper handles screen scroll and moves focus to button when step changes 
FormReviewSection:
- show if form is invalid in review section
- new component to show if review section has an error and display edit button
ReviewConfirm step:
- refactor to accept a list of items
Platform Application Page:
- scroll to top and focus on stepper button if form error on submit
- display generic error modal if api error on submit
> Platform - UI: Review section errors

- strr-api/src/strr_api/resources/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/22261
Allows receipt download for hosts.
> API - Get Account-Id from Request - `/<application_number>/payment/receipt`

- strr-web/components/bcros/form-section/property-manager/Form.vue
- strr-web/components/bcros/form-section/property/Form.vue
- strr-web/components/bcros/form-section/review/Form.vue
- strr-web/interfaces/account-i.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/create-account.vue
- strr-web/stores/strr.ts
- strr-web/tests/unit/pages/rental-application.spec.ts
- strr-web/utils/format-helper.ts
*Issue:*
- bcgov/entity/issues/23745
- On Review and Confirm page - add a checkbox when Property Manager exists
- Add validation, test update
> Add Host Authorization checkbox for Property Managers

- strr-web/components/bcros/stepper/StepperFooter.vue
- strr-web/package.json
- strr-web/pages/create-account.vue
- strr-web/tests/unit/components/stepper/StepperFooter.spec.ts
*Issue:*
- https://github.com/bcgov/entity/issues/23658
Fixes issue with applications being submitted multiple times.
> Host UI - Application Submit Button - Loading Animation

- strr-web/components/bcros/form-section/property/Details.vue
- strr-web/components/bcros/form-section/property/Form.vue
- strr-web/components/bcros/form-section/review/Form.vue
- strr-web/lang/en.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/tests/unit/components/form-section/property/Details.spec.ts
- strr-web/tests/unit/pages/rental-application.spec.ts
*Issue:*
- bcgov/entity/issues/23547
> 23547 uxa suggested changes

- strr-platform-web/app/composables/useStrrModals.ts
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/middleware/require-premium-account.ts
- strr-platform-web/app/pages/auth/account/choose-existing.vue
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/pages/platform/dashboard.vue
*Issue:*
Partial: 
- bcgov/entity#24117
- initial choose account page and middleware
- add strr product to user account on 'use this account' button click 
- decide if we care about mailing address
Still some todos.
> Platform - UI: Choose account page

- strr-base-web/package.json
- strr-base-web/pnpm-lock.yaml
> Base Layer: add missing country flag dep

- strr-web/components/bcros/status-card/StatusCard.vue
- strr-web/composables/useBcrosAuth.ts
- strr-web/package.json
- strr-web/pages/[...slug].vue
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/application-status.vue
- strr-web/pages/finalization.vue
- strr-web/pages/index.vue
- strr-web/pages/registration-details/[id]/index.vue
- strr-web/pages/registry-dashboard.vue
- strr-web/stores/account.ts
- strr-web/stores/keycloak.ts
- strr-web/tests/unit/composables/useBcrosAuth.spec.ts
- strr-web/tests/unit/stores/account.spec.ts
- strr-web/utils/axios.ts
*Issue:*
- bcgov/entity/issues/23663
- bcgov/entity/issues/24175
- bcgov/entity/issues/22830
- Update Account Flow to remove localStorage and bring back sessionStorage.
- Remove opening buttons/links in a new tab
- Redirect Hosts and Examiners to their Dashboards
- For non-existing URLs redirect user to the Dashboard
> Account Flow Fixes. Remove New Tabs. Redirects.

- strr-web/components/bcros/form-section/property/Details.vue
- strr-web/components/bcros/form-section/property/Form.vue
- strr-web/lang/en.json
- strr-web/pages/registration-details/[id]/index.vue
*Issue:*
- bcgov/entity/issues/23875
- bcgov/entity/issues/23547
> 23875 pid to examiner registration detail view

- jobs/auto-approval/devops/gcp/clouddeploy.yaml
> modify clouddeploy.yaml so it is a cloud run job

- strr-base-web/app/stores/tos.ts
> Platform/Strata - UI: update user in auth before fetching tos

- .github/workflows/strr-strata-ui-cd.yaml
- .github/workflows/strr-strata-ui-ci.yaml
- strr-strata-web/firebase.json
- strr-strata-web/vitest.config.ts
> UI - strata hotel CI/CD stuff

- strr-web/components/bcros/footer/Footer.vue
- strr-web/components/bcros/form-section/principal-residence/Form.vue
- strr-web/composables/useBcrosAuth.ts
- strr-web/package.json
- strr-web/page-data/breadcrumbs.ts
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/registration-details/[id]/index.vue
- strr-web/stores/keycloak.ts
*Issue:*
- bcgov/entity/issues/22830
- bcgov/entity/issues/23724
- bcgov/entity/issues/23663
- Update Account flow to redirect Examiner to Dashboard
- Clean session storage so the Account Select page shows up
- Fix Breadcrumb bug for Examiner on Details page
> Account Flow Updates. Breadcrumb Fix.

- strr-api/src/strr_api/requests/RegistrationRequest.py
- strr-api/src/strr_api/schemas/schemas/host-registration.json
- strr-api/tests/mocks/json/host_registration_property_manager.json
- strr-web/interfaces/property-manager-i.ts
- strr-web/package.json
- strr-web/pages/registry-dashboard.vue
- strr-web/stores/strr.ts
- strr-web/utils/formStateToApi.ts
*Issue:*
- https://github.com/bcgov/entity/issues/23532
> UI - Examiner Dashboard - PropertyManager Application Type Fix

- strr-base-web/app/locales/en-CA.ts
- strr-strata-web/app/components/modal/help/RegisterStrataHotel.vue
- strr-strata-web/app/components/modal/info/CollectionNotice.vue
- strr-strata-web/app/composables/useStrataModals.ts
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/app/pages/application.vue
- strr-strata-web/app/pages/auth/account/choose-existing.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/index.vue
- strr-strata-web/app/stores/strata.ts
- strr-strata-web/nuxt.config.ts
*Partial Issue:*
- bcgov/entity#24327
- add help modals to application page
- fix create new account button on choose account page
- update date column per scotts request
> Strata - UI: Help Modals & Date Column

- strr-web/composables/useBcrosAuth.ts
- strr-web/composables/useBcrosNavigate.ts
- strr-web/composables/useRegistrations.ts
- strr-web/composables/useTermsOfService.ts
- strr-web/lang/en.json
- strr-web/middleware/setupAuth.global.ts
- strr-web/package.json
- strr-web/pages/account-select.vue
- strr-web/pages/application-status.vue
- strr-web/pages/create-account.vue
- strr-web/pages/registry-dashboard.vue
- strr-web/pages/success/[id].vue
- strr-web/pages/success/[registrationId]/invoice/[paymentId].vue
- strr-web/pages/terms-of-service.vue
- strr-web/stores/account.ts
*Issue:*
- bcgov/entity/issues/23663
- bcgov/entity/issues/23691
- Update account flow to fix issues
- Fix label for middle name
> Fix Account Flow for Host

- strr-base-web/app/pages/auth/tos.vue
- strr-base-web/app/spa-loading-template.html
- strr-platform-web/package.json
*Partial Issue:*
- bcgov/entity#24327
- remove breadcrumbs on tos page
- add spa-loading-template so there is a loading state while the client is downloading the js bundle
> remove breadcrumb from tos page, add spa loading template

- strr-base-web/app/components/connect/detailsHeader/Item.vue
- strr-base-web/app/components/connect/detailsHeader/index.vue
- strr-base-web/app/composables/useStrrApi.ts
- strr-base-web/app/composables/useStrrBasePermit.ts
- strr-base-web/app/interfaces/connect-detail-header.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/stores/connectDetailsHeader.ts
- strr-base-web/app/utils/dashboardHelpers.ts
- strr-base-web/app/utils/download-file.ts
- strr-base-web/app/utils/formattingHelpers.ts
- strr-platform-web/app/interfaces/platform-api.ts
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/pages/platform/dashboard.vue
- strr-platform-web/app/stores/platform.ts
- strr-platform-web/app/utils/platform-application.ts
- strr-platform-web/app/utils/platform-side-details.ts
- strr-platform-web/nuxt.config.ts
- strr-platform-web/package.json
- strr-strata-web/app/interfaces/strata-api.ts
- strr-strata-web/app/pages/strata-hotel/dashboard/[registrationId].vue
- strr-strata-web/app/stores/strata.ts
- strr-strata-web/nuxt.config.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24327
> UI - platform/strata dashboard updates

- strr-base-web/app/components/connect/detailsHeader/Item.vue
- strr-platform-web/app/pages/platform/dashboard.vue
- strr-platform-web/package.json
- strr-strata-web/app/components/summary/Business.vue
- strr-strata-web/app/components/summary/RegOfficeAttorney.vue
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/app/pages/strata-hotel/dashboard/[registrationId].vue
- strr-strata-web/app/utils/strataDashboardHelpers.ts
- strr-strata-web/nuxt.config.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24323
> 24323 strata permit dashboard updates

- strr-base-web/app/composables/useStrrApi.ts
- strr-base-web/app/composables/useStrrBasePermit.ts
- strr-base-web/app/enums/registration-status.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/utils/dashboardHelpers.ts
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/pages/platform/dashboard.vue
- strr-platform-web/app/stores/platform.ts
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/app/pages/strata-hotel/dashboard/index.vue
- strr-strata-web/app/stores/strata.ts
> UI - account/permit dashboard load data updates

- strr-web/components/bcros/form-section/principal-residence/Form.vue
- strr-web/components/bcros/form-section/review/Form.vue
- strr-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/23856
Just updating the link.
> UI - Document Required Learn More Link Update

- strr-base-web/app/components/connect/detailsHeader/index.vue
- strr-base-web/app/interfaces/connect-detail-header.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/stores/connectDetailsHeader.ts
- strr-base-web/app/stores/strrContact.ts
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/pages/platform/dashboard.vue
- strr-platform-web/app/stores/platform.ts
- strr-platform-web/app/stores/platformApplication.ts
- strr-platform-web/app/stores/platformBusiness.ts
- strr-platform-web/app/stores/platformDetails.ts
- strr-platform-web/package.json
- strr-strata-web/app/pages/application.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/app/stores/strata.ts
- strr-strata-web/app/stores/strataApplication.ts
- strr-strata-web/app/stores/strataBusiness.ts
- strr-strata-web/app/stores/strataDetails.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24327
> UI - strata/platforms - reset stores and other tweaks

- strr-base-web/app/composables/useStrrBaseBusiness.ts
- strr-platform-web/app/components/form/platform/BusinessDetails.vue
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/pages/platform/dashboard.vue
- strr-platform-web/app/stores/platformApplication.ts
- strr-platform-web/app/stores/platformBusiness.ts
- strr-strata-web/app/components/form/BusinessDetails.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/app/stores/strataApplication.ts
- strr-strata-web/app/stores/strataBusiness.ts
*Issue:*
- bcgov/entity/issues/24327
> UI - platform/strata same as mailing business fixes

- strr-base-web/app/composables/useStrrBaseBusiness.ts
- strr-platform-web/app/stores/platformApplication.ts
> fix typo in base business composable

- strr-base-web/app/components/connect/contact/Bcros.vue
- strr-base-web/app/components/modal/Base.vue
- strr-host-pm-web/app/app.config.ts
- strr-host-pm-web/app/composables/useHostPmModals.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/middleware/choose-account-page.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/pages/auth/account/choose-existing.vue
- strr-host-pm-web/app/pages/auth/account/create-new.vue
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/app/pages/dashboard/index.vue
- strr-host-pm-web/nuxt.config.ts
*Issue:*
- bcgov/entity/issues/24467
- account creation screen/flow
- removed /strata-hotel route prefixes
> Host/PM - UI: Create account page

- strr-base-web/app/composables/useStrrModals.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/auth/account/create-new.vue
- strr-host-pm-web/nuxt.config.ts
*Issue:*
- bcgov/entity/issues/24517
- validate if account name exists in realtime
> Hosts: Account creation validation

- .github/workflows/strr-host-pm-ui-cd.yaml
- .github/workflows/strr-host-pm-ui-ci.yaml
> ci-cd for host pm

- .github/workflows/strr-base-web-ci.yaml
> add ci for base web

- .github/workflows/strr-base-web-ci.yaml
- .github/workflows/strr-host-pm-ui-cd.yaml
- .github/workflows/strr-host-pm-ui-ci.yaml
> update job name

- .github/workflows/strr-auto-approval-job-cd.yaml
- .github/workflows/strr-auto-approval-job-ci.yaml
- jobs/auto-approval/devops/gcp/clouddeploy.yaml
> job name too long

- .github/workflows/strr-auto-approval-job-cd.yaml
- .github/workflows/strr-auto-approval-job-ci.yaml
- jobs/auto-approval/devops/gcp/clouddeploy.yaml
> reduced name length more

- strr-web/composables/useApplications.ts
- strr-web/interfaces/document-upload-i.ts
- strr-web/package.json
- strr-web/pages/application-details/[id]/auto-approval/index.vue
- strr-web/pages/registration-details/[id]/index.vue
- strr-web/pages/staff-str-dashboard.vue
*Issue:*
- Refactor Registration Details to add appNum query param
> Refactor Registration Details page

- strr-web/package.json
*Issue:*
- bcgov/entity/issues/24717
> Update UI base version

- strr-base-web/app/components/connect/form/certify/index.vue
- strr-base-web/nuxt.config.ts
- strr-host-pm-web/app/components/form/UnitAddress/AutoComplete.vue
- strr-platform-web/.env.example
- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/stores/platformApplication.ts
- strr-platform-web/devops/vaults.env
- strr-platform-web/nuxt.config.ts
- strr-platform-web/package.json
- strr-strata-web/.env.example
- strr-strata-web/app/components/form/ReviewConfirm.vue
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/app/stores/strataApplication.ts
- strr-strata-web/devops/vaults.env
- strr-strata-web/nuxt.config.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24515
- bcgov/entity/issues/24516
- new common component for certify checkbox list (accept text or i18n key with dynamic props)
- update strata and platforms confirmation checkboxes
- 
> Strata/Platform - UI: Certify checkboxes

- strr-host-pm-web/app/components/form/ReviewConfirm.vue
- strr-host-pm-web/app/pages/application.vue
*Issue:*
- bcgov/entity/issues/24803
> UI - hosts stepper validation update

- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/dashboard/index.vue
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/app/stores/propertyRequirements.ts
*Issue:*
- bcgov/entity/issues/24809
- bcgov/entity/issues/24808
> Hosts dashboard/form fix

- strr-web/components/bcros/form-section/contact-information/SummaryView.vue
- strr-web/components/bcros/form-section/property-manager/SummaryView.vue
- strr-web/interfaces/property-manager-i.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/tests/mocks/mockPropertyManager.ts
- strr-web/tests/unit/pages/rental-application.spec.ts
- strr-web/tests/unit/utils/formStateToApi.spec.ts
- strr-web/utils/format-helper.ts
*Issue:*
Support Individual Property Managers for Examiners after API changes
> Support Individual Property Managers for Examiners

- strr-base-web/app/components/connect/accordion/Item.vue
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/utils/formattingHelpers.ts
- strr-base-web/app/utils/permitDashHelpers.ts
- strr-host-pm-web/app/interfaces/host-api.ts
- strr-host-pm-web/app/utils/host-formatting.ts
- strr-platform-web/app/pages/platform/dashboard.vue
*Issue:*
- bcgov/entity/issues/24769
Minor fixes for application submission and permit dash display
> UI - Hosts fixes

- strr-base-web/app/components/connect/accordion/Index.vue
- strr-base-web/app/interfaces/connect-accordion-item.ts
- strr-host-pm-web/app/utils/host-permit-dash-helpers.ts
*Issue:*
- bcgov/entity/issues/24769
- added blue icons in place of avatar letter for host:
> UI - permit dash sidebar avatar icon

- strr-host-pm-web/app/interfaces/property-requirements.ts
- strr-host-pm-web/app/stores/document.ts
- strr-host-pm-web/app/stores/propertyRequirements.ts
> UI - business license fix

- strr-base-web/app/app.config.ts
- strr-host-pm-web/app/components/form/AddOwners/input/Index.vue
*Issue:*
- bcgov/entity/issues/24600
- fix 'cancel' issue where certain fields would get updated (needed deep copy)
- update radios to be primary blue circles (requested by scott)
> UI - hosts small update

- strr-host-pm-web/app/components/form/AddOwners/input/Index.vue
- strr-host-pm-web/app/components/form/AddOwners/input/Person.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/app/stores/hostApplication.ts
- strr-host-pm-web/app/stores/hostOwner.ts
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/24856
- bcgov/entity/issues/24859
> 24856 hosts permit bl mapping

- strr-platform-web/app/pages/platform/dashboard.vue
- strr-platform-web/app/stores/platform.ts
- strr-strata-web/app/components/summary/Business.vue
- strr-strata-web/app/components/summary/RegOfficeAttorney.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/app/stores/strata.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24863
- bcgov/entity/issues/24624
- bcgov/entity/issues/24622
- bcgov/entity/issues/24623
> UI - Strata tweaks

- strr-base-web/app/composables/useStrrBasePermit.ts
- strr-base-web/app/error.vue
- strr-base-web/app/utils/todoItems.ts
- strr-platform-web/app/middleware/application-page.ts
- strr-platform-web/package.json
*Issue:*
- bcgov/entity/issues/24883
- bug when clicking begin application
- application override option fix
- update layout name in error.vue
> Platforms - UI: fix application page bug

- strr-base-web/app/stores/strrContact.ts
- strr-base-web/app/utils/permitDashHelpers.ts
- strr-host-pm-web/app/stores/hostOwner.ts
- strr-platform-web/package.json
*Issue:*
- bcgov/entity/issues/24857
> UI - first name optional

- strr-base-web/app/interfaces/contact.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/utils/formattingHelpers.ts
- strr-host-pm-web/app/components/form/AddOwners/input/Person.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitAddress.vue
- strr-host-pm-web/app/interfaces/host-api.ts
- strr-host-pm-web/app/interfaces/host-owner.ts
- strr-host-pm-web/app/interfaces/host-ui.ts
- strr-host-pm-web/app/stores/hostApplication.ts
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/app/utils/host-formatting.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/24855
> UI - hosts api mapping updates

- strr-host-pm-web/README.md
- strr-host-pm-web/firebase.json
> rename site in firebase json

- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/pages/auth/login.vue
- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/app/stores/platformBusiness.ts
- strr-platform-web/nuxt.config.ts
- strr-platform-web/package.json
*Issue:*
- bcgov/entity/issues/24510
- fix button colour on login screen
- update cpbc format
> Platforms - UI: Cpbc number

- strr-base-web/app/composables/useStrrBaseBusiness.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/utils/connect-validation/business-number.ts
- strr-base-web/app/utils/connect-validation/index.ts
- strr-host-pm-web/app/components/form/AddOwners/input/Business.vue
- strr-host-pm-web/app/components/form/AddOwners/input/Person.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitAddress.vue
- strr-host-pm-web/app/stores/hostOwner.ts
- strr-platform-web/app/components/form/platform/BusinessDetails.vue
- strr-platform-web/package.json
- strr-strata-web/app/components/form/BusinessDetails.vue
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24858
> UI - business number form hint / validation

- strr-host-pm-web/package.json
> Host UI version bump

- strr-host-pm-web/app/stores/hostOwner.ts
*Issue:*
- bcgov/entity/issues/24858
> UI - hosts reference fix

- strr-strata-web/app/app.config.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24957
- title
> Strata - UI: remove idir login from strata options

- .github/workflows/strr-ui-cd.yaml
- .github/workflows/strr-ui-ci.yaml
> add feature and examiner path to ci-cd

- strr-platform-web/.env.example
- strr-platform-web/app/components/form/platform/BusinessDetails.vue
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/devops/vaults.env
- strr-platform-web/nuxt.config.ts
- strr-platform-web/package.json
- strr-platform-web/pnpm-lock.yaml
*Issue:*
- bcgov/entity/issues/24508
- add learn more links
- downgrade nuxt (3.14 seems to have some issues)
> Platforms - UI: learn more links

- strr-host-pm-web/app/pages/auth/account/choose-existing.vue
- strr-host-pm-web/app/stores/document.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/24940
- title
> Host - UI: reset documents when requirements change

- .github/workflows/strr-api-cd.yaml
- .github/workflows/strr-auto-approval-job-cd.yaml
- .github/workflows/strr-examiner-ui-cd.yaml
- .github/workflows/strr-examiner-ui-ci.yaml
- .github/workflows/strr-host-pm-ui-cd.yaml
- .github/workflows/strr-pay-cd.yaml
- .github/workflows/strr-platform-ui-cd.yaml
- .github/workflows/strr-strata-ui-cd.yaml
> Update CD flows.

- strr-base-web/app/components/connect/fee/Widget.vue
- strr-base-web/app/composables/useStrrBasePermit.ts
- strr-base-web/app/enums/connect-payment-method.ts
- strr-base-web/app/interfaces/connect-pay-account.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/stores/connectFee.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/stores/hostApplication.ts
- strr-host-pm-web/package.json
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/stores/platformApplication.ts
- strr-platform-web/app/utils/account-change.ts
- strr-platform-web/nuxt.config.ts
- strr-platform-web/package.json
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25056
- allow cc override option in platforms
> Platform/Base - UI: Payment method override

- .github/PULL_REQUEST_TEMPLATE.md
*Issue:* n/a
Fixing the PR template
> fixing the PR template

- strr-base-web/app/components/form/common/Contact.vue
- strr-host-pm-web/app/components/form/AddOwners/input/Person.vue
- strr-host-pm-web/app/components/form/Review/Index.vue
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/stores/document.ts
- strr-host-pm-web/app/stores/hostOwner.ts
- strr-host-pm-web/nuxt.config.ts
- strr-host-pm-web/package.json
- strr-platform-web/package.json
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25093
- bcgov/entity/issues/25101
- bcgov/entity/issues/25099
- bcgov/entity/issues/25098
- bcgov/entity/issues/25089
- bcgov/entity/issues/25097
> Host - UI: Bug fixes

- strr-host-pm-web/app/components/form/AddDocuments/index.vue
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/stores/document.ts
- strr-host-pm-web/app/types/document-type-key.ts
- strr-host-pm-web/nuxt.config.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25119
- bcgov/entity/issues/25113
> Host - UI: Documents fix

- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25113
- remove all exemption docs when user unselects exempt checkbox
> Host - UI: remove exemption docs if user unselects theyre exempt

- strr-host-pm-web/app/components/form/AddDocuments/index.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitDetails.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/List.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/StrProhibited.vue
- strr-host-pm-web/app/components/form/Review/Index.vue
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-1.test.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-3.test.ts
- strr-host-pm-web/tests/e2e/test-utils/upload-documents.ts
*Issue:*
- bcgov/entity/issues/25137
- e2e test scenario 1
- add step 1 requirements list assertions 
- add step 3 required docs list assertions
- add step 4 pr declaration in confirmation list assertion
https://github.com/user-attachments/assets/8a3c8c2e-b641-4e74-b374-041ba127657d
> Host - UI: Scenario 1 e2e test

- strr-web/components/bcros/form-section/contact-information/SummaryView.vue
- strr-web/interfaces/account-i.ts
- strr-web/interfaces/application-i.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/application-details/[id]/index.vue
- strr-web/pages/staff-str-dashboard.vue
- strr-web/tests/mocks/mockApplication.ts
- strr-web/tests/unit/pages/application-details.spec.ts
*Issue:*
- bcgov/entity/issues/25145
- Fix Examiner Dash and Details page
> Fix Examiner Dash and Details page

- strr-host-pm-web/app/components/form/AddDocuments/index.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitAddress.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/Error.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/PrExempt.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/index.vue
- strr-host-pm-web/app/stores/hostProperty.ts
- strr-host-pm-web/package.json
- strr-host-pm-web/playwright.config.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-2.test.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-4.test.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-5.test.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-6.test.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-7.test.ts
- strr-host-pm-web/tests/e2e/smoke-tests/Scenario-8.test.ts
*Issue:*
- bcgov/entity/issues/25163
- complete e2e tests for scenarios 4-7 + address not found scenario
- tests fail when run in parallel so need to spend some time sorting this out
> Hosts - UI: Playwright e2e tests

- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/utils/formattingHelpers.ts
- strr-base-web/app/utils/todoItems.ts
- strr-host-pm-web/app/interfaces/host-api.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/stores/hostApplication.ts
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/package.json
- strr-platform-web/app/interfaces/platform-api.ts
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/app/stores/platform.ts
- strr-platform-web/app/stores/platformApplication.ts
- strr-platform-web/app/utils/platform-application.ts
- strr-platform-web/package.json
- strr-strata-web/app/pages/strata-hotel/application.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/index.vue
- strr-strata-web/app/stores/strata.ts
- strr-strata-web/app/stores/strataApplication.ts
- strr-strata-web/app/utils/strata-formating.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25154
- small UI fixes for hosts drafts
- implemented UI strata drafts
- implemented UI platform drafts
> UI - finished drafts

- strr-strata-web/.env.example
- strr-strata-web/app/components/form/StrataDetails.vue
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/devops/vaults.env
- strr-strata-web/nuxt.config.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25283
- title
> Strata - UI: add 2nd link in docs upload description text

- strr-host-pm-web/app/components/form/AddOwners/Index.vue
- strr-host-pm-web/app/components/summary/Owners.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/package.json
*Issue:*
- [bcgov/entity/issues/25725](https://github.com/bcgov/entity/issues/25275)
- updated per figma design
- empty state
- update text
Ran against scenario 1 e2e test, still passing
https://github.com/user-attachments/assets/3e7e2aa9-bffc-4916-8e84-16057e75d4a3
> Host - UI: add empty state to step2 table

- strr-web/enums/pr-exemption-reason-e.ts
- strr-web/interfaces/application-i.ts
- strr-web/lang/en.json
- strr-web/package.json
- strr-web/pages/application-details/[id]/index.vue
*Issue:*
- bcgov/entity/issues/25279
- Legacy Examiner - Add PR Exempt Reason on Details page
> Legacy Examiner - Add PR Exempt Reason

- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/HostDetailsView.vue
- strr-examiner-web/app/components/NavigationTabs.vue
- strr-examiner-web/app/layouts/examiner.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/24535
- Examiner table: Add PR Requirements column (Strata requirements pending API changes)
- Update table columns, add Manager & Host info, make row clickable, etc.
- Small refactoring of components, small styling updates
> Update Examiner Table. Add PR Requirements.

- strr-host-pm-web/app/interfaces/host-api.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/stores/hostApplication.ts
- strr-host-pm-web/package.json
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/package.json
- strr-strata-web/app/interfaces/strata-api.ts
- strr-strata-web/app/pages/strata-hotel/application.vue
- strr-strata-web/app/stores/strataApplication.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25239
- add user selected payment option to the header for hosts/strata
- use draft id / PUT when available for application submit
> UI - small fixes

- docs/oas/platform.yaml
*Issue:*  bcgov/entity#25363
Initial draft of the OpenAPI spec for the platform API.
> feat(api): initial draft of the platform spec

- strr-host-pm-web/README.md
- strr-platform-web/README.md
- strr-strata-web/README.md
*Issue:*
- bcgov/entity/issues/25349
- update readmes with section about sbc web messenger
> Host/Strata/Platform - UI: update test readme section

- strr-base-web/nuxt.config.ts
- strr-base-web/package.json
- strr-base-web/pnpm-lock.yaml
- strr-host-pm-web/.env.example
- strr-host-pm-web/devops/vaults.env
- strr-host-pm-web/package.json
- strr-platform-web/.env.example
- strr-platform-web/devops/vaults.env
- strr-platform-web/package.json
- strr-strata-web/.env.example
- strr-strata-web/devops/vaults.env
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24997
- add gtag module and config
> add google analytics

- strr-base-web/app/stores/tos.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/app/pages/dashboard/index.vue
- strr-host-pm-web/package.json
- strr-platform-web/package.json
- strr-strata-web/app/pages/strata-hotel/application.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/app/pages/strata-hotel/dashboard/index.vue
- strr-strata-web/package.json
*Issue:*
- refresh token before fetching tos
- add check tos middleware to dashboard pages
> fix: refresh token

- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/Strata/SubHeader.vue
- strr-examiner-web/app/components/Strata/SupportingInfo.vue
- strr-examiner-web/app/components/StrataHotelDetailsView.vue
- strr-examiner-web/app/components/SupportingDocuments.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/app/utils/format-helper.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/25191
- Strata Details page
- Expansion components will come in next PR
> Strata Details page - Part 1/2

- strr-base-web/nuxt.config.ts
- strr-host-pm-web/package.json
- strr-platform-web/package.json
- strr-strata-web/package.json
> Host/Strata/Platforms: add back in gtag and bump versions

- strr-base-web/app/components/connect/InfoWithIcon.vue
- strr-base-web/app/components/connect/form/address/Display.vue
- strr-base-web/app/utils/connect-address.ts
- strr-base-web/app/utils/formattingHelpers.ts
- strr-base-web/app/utils/permitDashHelpers.ts
- strr-examiner-web/app/components/Common/SubHeaderTemplate.vue
- strr-examiner-web/app/components/Platform/Expansion/Brands.vue
- strr-examiner-web/app/components/Platform/Expansion/Business.vue
- strr-examiner-web/app/components/Platform/Expansion/Parties.vue
- strr-examiner-web/app/components/Platform/SubHeader.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/stores/examiner.ts
*Issue:*
- bcgov/entity/issues/25315
- expansions are still a wip
> UI - examiner platform details

- strr-examiner-web/app/components/Common/ExpansionTemplate.vue
- strr-examiner-web/app/components/Platform/Expansion/Brands.vue
- strr-examiner-web/app/components/Platform/Expansion/Business.vue
- strr-examiner-web/app/components/Platform/Expansion/Parties.vue
- strr-examiner-web/app/components/Platform/SubHeader.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/25315
expansions:
at 4 06 58 PM](https://github.com/user-attachments/assets/aea91795-a366-4d3b-8763-053b66e3d659)
> UI - examiner platform details expansion cleanup

- strr-examiner-web/devops/vaults.env
- strr-examiner-web/package.json
- Update `vaults.env` for Examiner
> Update Examiner vaults

- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/package.json
- Update account login flow by removing `require-account` middleware
> Remove require-account Middleware

- strr-host-pm-web/app/components/form/DefineYourRental/UnitDetails.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25451
> Host - UI: update alert text

- strr-api/pyproject.toml
- strr-api/src/strr_api/services/payment_service.py
*Issue:*
- bcgov/entity/issues/25338
- update host fee to HOSTREG_3 if propertyType is B&B or recreational
> Api: host fee update

- strr-api/src/strr_api/services/payment_service.py
*Issue:*
- bcgov/entity/issues/25423
> Api: host fee code check fix

- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/app/locales/en-CA.ts
- strr-platform-web/package.json
- strr-strata-web/app/components/form/ReviewConfirm.vue
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/25331
Text changes
> UI - Platform & Strata T&C Text Update

- strr-base-web/app/enums/strr-fee-code.ts
- strr-host-pm-web/app/app.config.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/stores/hostProperty.ts
- strr-host-pm-web/nuxt.config.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25424
- update for different fee code if property type is B&B or Recreational
> Host UI fee update

- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/Host/SupportingInfo.vue
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/mocks/mockedData.ts
- strr-examiner-web/tests/plugins/data-test-id.ts
- strr-examiner-web/tests/setup.ts
- strr-examiner-web/tests/unit/application-details.spec.ts
- strr-examiner-web/tests/unit/dashboard.spec.ts
- strr-examiner-web/vitest.config.ts
- strr-web/components/bcros/form-section/property-manager/Form.vue
*Issue:*
- bcgov/entity/issues/25462
- Add tests for Examiner Dashboard and Application Details pages
> Add Unit Tests for Examiner

- .github/workflows/strr-email-cd.yaml
- .github/workflows/strr-email-ci.yaml
- queue_services/strr-email/devops/gcp/clouddeploy.yaml
- queue_services/strr-email/poetry.lock
- queue_services/strr-email/setup.cfg
- queue_services/strr-email/src/strr_email/config.py
- queue_services/strr-email/src/strr_email/resources/email_listener.py
*Issue:*
- bcgov/entity/issues/25558
ci-cd for the job located at: https://github.com/bcgov/STRR/tree/main/queue_services/strr-email
> 25558- ci-cd for strr email

- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/List.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/StrProhibited.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/index.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25532
> Host - UI: update str prohibited alert

- strr-base-web/app/locales/en-CA.ts
- strr-strata-web/package.json
- strr-strata-web/tests/mocks/i18n.ts
*Issue:*
- bcgov/entity/issues/25479
title
> Strata - UI: remove period from category options

- strr-host-pm-web/app/components/form/DefineYourRental/UnitDetails.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/stores/hostProperty.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25570
> Host - UI: Optional pid

- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/25586
On:
Off: 
> Examiners - UI: ld flag

- queue_services/strr-email/email-templates/common/strr-important-next-steps.md
*Issue:*
- bcgov/entity/issues/22866
- bcgov/entity/issues/24893
- bcgov/entity/issues/25296
- wording tweak
> Host email template wording tweak

- queue_services/strr-email/src/strr_email/config.py
- queue_services/strr-email/src/strr_email/resources/email_listener.py
- strr-api/src/strr_api/resources/application.py
- strr-api/src/strr_api/responses/RegistrationSerializer.py
- strr-api/src/strr_api/services/application_service.py
- strr-api/src/strr_api/services/registration_service.py
- strr-api/tests/postman/strr-api.postman_collection.json
*Issue:*
- bcgov/entity/issues/25474
tweaks to email:
- bcgov/entity/issues/22866
- bcgov/entity/issues/24893
- bcgov/entity/issues/25296
- bcgov/entity/issues/25297
> API - endpoint for existing host registrations

- .github/workflows/strr-examiner-ui-cd.yaml
*Issue:*
https://github.com/pnpm/pnpm/issues/9029
https://github.com/nodejs/corepack/issues/612
https://github.com/bcgov/bcregistry-sre/pull/215/files
> CI: Update pnpm version in examiner UI workflow

- strr-examiner-web/pnpm-lock.yaml
> update lock file

- .github/workflows/strr-host-pm-ui-cd.yaml
- .github/workflows/strr-platform-ui-cd.yaml
- .github/workflows/strr-strata-ui-cd.yaml
- .github/workflows/strr-ui-cd.yaml
> add pnpm version to frontend cd

- strr-host-pm-web/pnpm-lock.yaml
- strr-platform-web/pnpm-lock.yaml
- strr-strata-web/pnpm-lock.yaml
> lock files

- .github/workflows/strr-examiner-ui-ci.yaml
> testing ci

- .github/workflows/strr-host-pm-ui-ci.yaml
- .github/workflows/strr-platform-ui-ci.yaml
- .github/workflows/strr-strata-ui-ci.yaml
> adding pnpm version

- strr-base-web/app/app.vue
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/pages/auth/login.vue
- strr-base-web/package.json
- strr-base-web/pnpm-lock.yaml
- strr-examiner-web/.env.example
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/devops/vaults.env
- strr-examiner-web/package.json
- strr-examiner-web/pnpm-lock.yaml
- strr-host-pm-web/.env.example
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/devops/vaults.env
- strr-host-pm-web/nuxt.config.ts
- strr-host-pm-web/package.json
- strr-host-pm-web/pnpm-lock.yaml
- strr-platform-web/.env.example
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/devops/vaults.env
- strr-platform-web/package.json
- strr-platform-web/pnpm-lock.yaml
- strr-strata-web/.env.example
- strr-strata-web/app/pages/strata-hotel/application.vue
- strr-strata-web/devops/vaults.env
- strr-strata-web/package.json
- strr-strata-web/pnpm-lock.yaml
*Issue:*
- bcgov/entity/issues/25445
https://github.com/user-attachments/assets/cd27944a-465e-4f61-b0e0-8fcb97073a7c
> Host/Strata/Platform/Examiner -UI: Session timeout

- strr-host-pm-web/pnpm-lock.yaml
> Host - fix

- strr-examiner-web/package.json
- strr-examiner-web/pnpm-lock.yaml
- strr-platform-web/package.json
- strr-platform-web/pnpm-lock.yaml
- strr-strata-web/package.json
- strr-strata-web/pnpm-lock.yaml
> Examiner/Platform/Strata - Fix pnpm lockfile

- strr-examiner-web/app/components/Host/SubHeader.vue
- strr-examiner-web/app/components/Strata/Expansion/Business.vue
- strr-examiner-web/app/components/Strata/SubHeader.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/package.json
- strr-examiner-web/tests/mocks/mockedData.ts
- strr-examiner-web/tests/unit/host-application-details.spec.ts
- strr-examiner-web/tests/unit/strata-application-details.spec.ts
*Issue:*
- bcgov/entity/issues/25589
- Add Approve/Refuse buttons to Strata Hotel
- Small misc updates
- Unit tests
> Add Approve & Refuse buttons to Strata Hotel

- queue_services/strr-email/email-templates/common/strr-footer.md
- queue_services/strr-email/email-templates/common/strr-important-next-steps.md
- queue_services/strr-email/src/strr_email/config.py
- queue_services/strr-email/src/strr_email/resources/email_listener.py
- strr-base-web/app/components/connect/form/address/Index.vue
- strr-base-web/package.json
*Issue:*
- bcgov/entity/issues/26130
- bcgov/entity/issues/26111
- Fix Province validation fix
- Update Automate Email text
> Hotfix - Province Validation Fix and Automated Emails Text

- strr-host-pm-web/package.json
- strr-platform-web/package.json
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/26130
- bcgov/entity/issues/26111
- Update versions UI app to get latest base layer
> Hotfix - Update versions UI apps

- strr-base-web/app/components/connect/form/address/Index.vue
- strr-base-web/package.json
*Issue:*
- bcgov/entity/issues/26130
- Update base layer to support hotfix
> Update base layer to support hotfix

- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/25531
> UI - Add Missing Validation Function in handleSubmit

- strr-examiner-web/app/components/Strata/SubHeader.vue
- strr-examiner-web/app/pages/dashboard.vue
*Issue:*
- bcgov/entity/issues/25635
- Fix PR Requirements column
- Fix Strata Address, to display full address (see screenshot)
> Fix Examiners Dashboard - PR and Strata Address

- strr-examiner-web/app/components/Host/SupportingInfo.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
- strr-host-pm-web/app/components/summary/Property.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/25943
Also include the following fixes:
> UI - Property type and other text Updates

- strr-base-web/app/composables/useStrrApi.ts
- strr-base-web/app/enums/applications-sort-e.ts
- strr-base-web/package.json
- strr-examiner-web/.eslintrc
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/unit/dashboard.spec.ts
*Issue:*
- bcgov/entity/issues/26041
- bcgov/entity/issues/26093
- Display application number and registration number (requires to show all statuses)
- Show applications ordered by oldest first
- Update getNext application logic to show oldest submitted app
- Small visual and content updates
> Examiner Dashboard Updates

- strr-base-web/app/stores/strrContact.ts
- strr-base-web/package.json
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25882
- Correctly Pre-populate Host First name
> Fix Host Name Pre-Population 

- strr-api/pyproject.toml
- strr-api/src/strr_api/responses/RegistrationSerializer.py
- strr-api/tests/unit/resources/test_registrations.py
*Issue:*
- https://github.com/bcgov/entity/issues/26026
- https://github.com/bcgov/entity/issues/26281
- Added Examiner and Host statuses and actions for registration
- Added additional attributes needed to support Examiner Registration View (including CompletingParty and existingHostRegistrations)
> API - Examiner Registration View

- .github/workflows/strr-api-cd.yaml
- .github/workflows/strr-auto-approval-job-cd.yaml
- .github/workflows/strr-email-cd.yaml
- .github/workflows/strr-examiner-ui-cd.yaml
- .github/workflows/strr-host-pm-ui-cd.yaml
- .github/workflows/strr-pay-cd.yaml
- .github/workflows/strr-platform-ui-cd.yaml
- .github/workflows/strr-strata-ui-cd.yaml
- .github/workflows/strr-ui-cd.yaml
- jobs/auto-approval/devops/gcp/clouddeploy.yaml
- queue_services/strr-email/devops/gcp/clouddeploy.yaml
- queue_services/strr-pay/devops/gcp/clouddeploy.yaml
- strr-api/devops/gcp/clouddeploy.yaml
> add uat to clouddeploy and cd files

- jobs/auto-approval/devops/gcp/clouddeploy.yaml
- queue_services/strr-email/devops/gcp/clouddeploy.yaml
- queue_services/strr-pay/devops/gcp/clouddeploy.yaml
- strr-api/devops/gcp/clouddeploy.yaml
> update target id

- .github/workflows/strr-noc-expiry-cd.yaml
- .github/workflows/strr-nod-expiry-ci.yaml
> fix wrong name

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/26241
> API - Add `SEND_NOC` examiner action

- strr-base-web/app/components/BaseUploadAdditionalDocuments.vue
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/interfaces/ui-document.ts
*Issue:*
- Add `BaseUploadAdditionalDocuments` to be used in Host and Strata app for NOC
> Add BaseUploadAdditionalDocuments component

- .github/workflows/strr-batch-validator-listener-cd.yaml
- .github/workflows/strr-batch-validator-listener-ci.yaml
> update app name

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/26241
> API - Remove REJECT examiner action - FULL_REVIEW application status

- .github/workflows/strr-batch-validator-job-cd.yaml
- .github/workflows/strr-batch-validator-listener-cd.yaml
> tag for uat

- strr-base-web/app/utils/date.ts
- strr-base-web/package.json
- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26241
> UXA - Examiner NOC

- strr-api/src/strr_api/resources/validation.py
- strr-api/tests/unit/resources/test_validation.py
*Issue:*
Added the :action to the permit url
Did not mount the permit under v1
> added the url colon action

- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/26093
- UXA feedback
> UXA: Fix icon styling in Examiner app

- strr-base-web/app/components/todo/Index.vue
- strr-base-web/app/interfaces/todo.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/utils/todoItems.ts
- strr-base-web/package.json
*Issue:*
- bcgov/entity/issues/26437
- To Do item for NOC - Base Layer prep work for below screenshot
> To Do item for NOC (Prep work)

- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/unit/application-dashboard.spec.ts
- strr-platform-web/app/pages/platform/dashboard.vue
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/26437
- To Do NOC for Host and Strata
- Unit test
> To Do NOC item for Host and Strata

- strr-base-web/app/components/todo/Index.vue
- strr-examiner-web/app/components/ApplicationDetailsSection.vue
- strr-examiner-web/app/components/Host/SubHeader.vue
- strr-examiner-web/app/components/Host/SupportingInfo.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/mocks/mockedData.ts
- strr-examiner-web/tests/unit/host-application-details.spec.ts
*Issue:*
- bcgov/entity/issues/26234
- View NOC Documents on Examiner Dashboard
- Test coming up in next commit
> View NOC Documents on Examiner Dashboard

- strr-base-web/app/components/todo/Index.vue
- strr-base-web/app/locales/en-CA.ts
*Issue:*
- bcgov/entity/issues/26437
- UXA updates for To Do items for Host
> UXA updates for To Do items for Host

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/models/dataclass.py
- strr-api/src/strr_api/resources/application.py
- strr-api/tests/postman/strr-api.postman_collection.json
- strr-api/tests/unit/resources/test_registration_applications.py
*Issue:*
- https://github.com/bcgov/entity/issues/26261
> API - Registration Number Filter

- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26261
- relies on #619 
> UI - Registration Number Filter

- queue_services/batch-permit-validator/devops/gcp/clouddeploy.yaml
> deply env tag issue in sandbox

- jobs/auto-approval/devops/gcp/clouddeploy.yaml
- jobs/batch-permit-validator/devops/gcp/clouddeploy.yaml
- jobs/noc_expiry/devops/gcp/clouddeploy.yaml
- queue_services/strr-email/devops/gcp/clouddeploy.yaml
- queue_services/strr-pay/devops/gcp/clouddeploy.yaml
> upodate deploy env

- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26344
> Examiner UI - Able to View Application Receipt

- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/25613
https://github.com/bcgov/entity/issues/25613#issuecomment-2743863297
> Examiner UI - Hide NOC Email

- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/package.json
- strr-examiner-web/tests/unit/host-application-details.spec.ts
- strr-examiner-web/tests/unit/registration-details.spec.ts
*Issue:*
- https://github.com/bcgov/entity/issues/26344
> Examiner UI - View Receipt UXA Updates

- strr-examiner-web/app/components/Host/SubHeader.vue
- strr-examiner-web/app/components/Platform/SubHeader.vue
- strr-examiner-web/app/components/Strata/SubHeader.vue
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/26521
- Fix styling to wrap long names on Examiner Details View
> Fix Long Name Wrapping

- strr-examiner-web/app/components/Host/SubHeader.vue
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/26521
- Fix long words wrapping in Examiner Details View
> Fix long words wrapping in Examiner Details View

- strr-api/migrations/versions/20250327_1155_9c8f72d31a5e_.py
- strr-api/pyproject.toml
- strr-api/src/strr_api/enums/enum.py
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/models/dataclass.py
- strr-api/src/strr_api/models/events.py
- strr-api/src/strr_api/resources/application.py
- strr-api/src/strr_api/services/application_service.py
- strr-api/src/strr_api/services/validation_service.py
- strr-api/tests/postman/strr-api.postman_collection.json
- strr-api/tests/postman/strr-api.postman_environment.json
- strr-api/tests/unit/resources/test_registration_applications.py
*Issue:*
- https://github.com/bcgov/entity/issues/26655
- https://github.com/bcgov/entity/issues/26653
> API - Assign & Un-assign Applications

- strr-base-web/app/utils/date.ts
- strr-base-web/package.json
- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26841
> Examiner UI - NOC Expiry Time Fix

- strr-examiner-web/app/components/Table/Header/Select.vue
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/stores/examiner.ts
*Issue:*
- https://github.com/bcgov/entity/issues/26655
> Examiner UI UXA Updates

- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26657
Follow up from https://github.com/bcgov/STRR/pull/658
> Examiner UI - Default Statuses

- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26657
> Examiner UI - Status Filter Bug Fix

- strr-base-web/app/utils/todoItems.ts
- strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/26811
- Fix scroll in Strata NOC To Do
> Fix scroll in Strata NOC To Do

- jobs/provisional-approval/devops/vaults.gcp.env
> add quote in vault file

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/models/dataclass.py
- strr-api/src/strr_api/resources/application.py
- strr-api/tests/unit/resources/test_registration_applications.py
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/27083
> Hotfix - Draft applications not visible in Host, Platform & Strata App

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/src/strr_api/models/dataclass.py
- strr-api/src/strr_api/resources/application.py
- strr-api/tests/unit/resources/test_registration_applications.py
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/27083
Initally changes were merged to `hotfix-27083` branch and deployed to test and QAed.
This PR is merging those changes with `main`
> Hotfix - Draft applications (27083) - Merge Changes to Main

- strr-base-web/app/composables/useFeatureFlags.ts
- strr-base-web/app/composables/useStrrApi.ts
- strr-base-web/app/enums/registration-todo-type.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/locales/en-CA.ts
- Ground work for the Renewals to be available in Base layer
- Needs to be merged before Host Renewals To Do
> Base Layer Updates for Reg Renewals

- strr-base-web/app/composables/useFeatureFlags.ts
- strr-base-web/app/composables/useStrrApi.ts
> Cleanup Base Layer

- strr-base-web/app/components/todo/Index.vue
- strr-base-web/app/enums/registraation-todo-type.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/app/utils/todoItems.ts
- strr-base-web/package.json
- strr-host-pm-web/app/composables/useRenewals.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/mocks/mockedData.ts
- strr-host-pm-web/tests/unit/application-dashboard.spec.ts
*Issue:*
- bcgov/entity/issues/26826
- Add Reg Renewals To Do for Hosts
- 3 ToDos: Ready for Renew, Expired, Closed
- Add Feature Flag
- Update unit test
> Host Renewal To Do

- strr-base-web/app/composables/useStrrBasePermit.ts
- strr-base-web/app/enums/registraation-todo-type.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/utils/todoItems.ts
- strr-base-web/package.json
- strr-host-pm-web/app/composables/useRenewals.ts
- strr-host-pm-web/app/composables/useRouterParams.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/app/pages/dashboard/index.vue
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/unit/application.spec.ts
- strr-host-pm-web/tests/unit/registration-renewal.spec.ts
*Issue:*
- bcgov/entity/issues/26829
- bcgov/entity/issues/26842
- Prefill Application form with Registration data
- Use `renewal=true&registrationId=...` as query/router params to open the renewal application
- Add unit test
> Open Registration Renewal. Fix NOC Exp Date.

- strr-base-web/app/components/form/ContactInfo.vue
- strr-base-web/package.json
- strr-host-pm-web/app/components/form/AddOwners/input/Person.vue
- strr-host-pm-web/package.json
*Issue:*
- Allow First & Last Name Inputs for BCeID
> Allow First & Last Name Inputs for BCeID

- strr-base-web/app/stores/strrContact.ts
- strr-base-web/package.json
- strr-host-pm-web/app/components/form/AddOwners/input/Person.vue
- strr-platform-web/app/components/form/platform/ReviewConfirm.vue
- strr-platform-web/package.json
- strr-strata-web/app/components/form/ReviewConfirm.vue
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/27108
- Fix validation on Step 1 for Strata and Platforms for BCeID users
- Update Review page
> Fix Strata and Platform for BCeID users

- strr-base-web/app/locales/en-CA.ts
- strr-base-web/package.json
- strr-host-pm-web/app/components/form/AddDocuments/index.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/package.json
- strr-strata-web/app/components/form/StrataDetails.vue
- strr-strata-web/app/locales/en-CA.ts
- strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/27134
- Allow Image Upload for Hosts and Strata
- Text updates
> Allow Image Upload for Hosts and Strata

- queue_services/strr-email/email-templates/common/strr-important-deadlines.md
*Issue:* bcgov/entity#27497
Changed dates
**From**
May 1, 2025: 
June 1, 2025: 
**To** 
June 2, 2025: 
June 23, 2025: 
> feat(api): change deadlines in common file as per bcgov/entity#27497

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-api/tests/unit/resources/test_registration_applications.py
> Sync Changes from HotFix - Update NOC status

- strr-api/pyproject.toml
- strr-api/src/strr_api/responses/EventsResponse.py
- strr-api/src/strr_api/services/application_service.py
*Issue:*
- https://github.com/bcgov/entity/issues/26906
> API - IDIR in Application & Registration Events

- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
*Issue:*
- https://github.com/bcgov/entity/issues/27281
> UX Changes - Examiner UI Updates

- strr-base-web/app/components/BaseUploadAdditionalDocuments.vue
- strr-base-web/app/locales/en-CA.ts
- Sync Recent Hotfixes: 27497 27387
> Sync Hotfix 27497 27387

- strr-api/pyproject.toml
- strr-api/src/strr_api/services/payment_service.py
- strr-examiner-web/app/layouts/examine.vue
- strr-examiner-web/app/layouts/examiner.vue
- strr-examiner-web/app/pages/dashboard.vue
*Issue:*
- https://github.com/bcgov/entity/issues/27038
- https://github.com/bcgov/entity/issues/27056
- https://github.com/bcgov/entity/issues/27163
> Examiner UI Fixes and Folio in Receipt

- strr-base-web/app/composables/useStrrModals.ts
- strr-base-web/package.json
- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/Host/Expansion/EditRentalUnitForm.vue
- strr-examiner-web/app/components/Host/SubHeader.vue
- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/app/composables/useExaminerActions.ts
- strr-examiner-web/app/composables/useExaminerRoute.ts
- strr-examiner-web/app/composables/useHostExpansion.ts
- strr-examiner-web/app/enums/actions.ts
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/package.json
- strr-examiner-web/pnpm-lock.yaml
- strr-examiner-web/tests/unit/host-application-details.spec.ts
*Issue:*
- bcgov/entity/issues/27447
- Update dependencies versions 
- Approve Application functionality
- Confirmation Modal
- Small fixes
> Examiner - Approve a Provisional Application

- strr-examiner-web/app/components/ComposeNoc.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/27284
- Send NOC for Provisional Review Application
- Add Confirmation Dialog for Send NOC
> Send NOC for Provisional Review Application

- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
> Fix Provisionally Approved Submission

- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/stores/examiner.ts
*Issue:*
- bcgov/entity/issues/27449
- Fix payload for Set Aside
> Update Set Aside Application Payload

- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/package.json
- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/27522
- Examiner: Rename Cancel -> Cancel Registration
> Add Cancelled Registration Date in Details View

- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/package.json
- strr-platform-web/app/pages/platform/application.vue
- strr-platform-web/package.json
- strr-strata-web/app/pages/strata-hotel/application.vue
- strr-strata-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/28433
> UI - Prevent Save Button from Creating Multiple Draft Applications

- .github/workflows/strr-registration-expiry-job-cd.yaml
- .github/workflows/strr-registration-expiry-job-ci.yaml
> ci-cd for reg expiry

- strr-base-web/app/components/connect/form/address/DisplayItem.vue
- strr-base-web/package.json
- strr-host-pm-web/app/components/summary/Property.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/28713
> UI - Host Dashboard Property Address Breakdown

- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/28595
- Update wording in Cancel Reg modal
> Update wording in Cancel Reg modal

- strr-host-pm-web/app/composables/useRenewals.ts
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/unit/application-dashboard.spec.ts
*Issue:*
- bcgov/entity/issues/26826
- Fix reactivity for Reg Renewals ToDos for Hosts
- Update unit tests
> Update ToDo for Reg Renewals

- strr-examiner-web/app/components/Host/Expansion/FilingHistory.vue
- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/app/composables/useExaminerRoute.ts
- strr-examiner-web/app/enums/actions.ts
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/app/types/application-response.ts
*Issue:*
- https://github.com/bcgov/entity/issues/28464
> UI - Set Aside Registration

- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/28464
> UXA - Set Aside Registration Text Update

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/27456
- https://github.com/bcgov/entity/issues/28988
Rework using application header approach
> API - Registration Address - Host & Examiner UI List View

- strr-api/pyproject.toml
- strr-api/src/strr_api/services/application_service.py
*Issue:*
- https://github.com/bcgov/entity/issues/28514
> API Fix - Add cancelled_date for Provisional Application Workflow 

- strr-examiner-web/app/composables/useExaminerActions.ts
- strr-examiner-web/app/composables/useExaminerRoute.ts
- strr-examiner-web/app/enums/actions.ts
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- Add Suspend Registration
- Confirmation Modal
- Feature Flag  
> Add Suspend Registration

- strr-base-web/app/enums/registration-noc-status.ts
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/package.json
*Issue:*
- Base app updates for Reg NOC for Hosts
> Base App Updates for Reg NOC for Hosts

- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/27522
> UI - Cancel Registration Email

- strr-examiner-web/app/components/SupportingDocuments.vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/28860
- Open Reg NOC docs in a new tab
> Examiner View Reg NOC Docs

- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/app/composables/useExaminerRoute.ts
- strr-examiner-web/app/enums/actions.ts
- strr-examiner-web/app/enums/registration-noc-status.ts
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/28862
> UI - Examiner Can Send Registration NOC

- strr-api/pyproject.toml
- strr-api/src/strr_api/models/application.py
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/package.json
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/dashboard/index.vue
- strr-host-pm-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/29453
> Add Registration NOC alert in Host Dashboard List View

- strr-api/pyproject.toml
- strr-api/src/strr_api/resources/registrations.py
- strr-base-web/app/components/todo/Index.vue
- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/app/interfaces/todo.ts
- strr-base-web/app/locales/en-CA.ts
- strr-base-web/package.json
- strr-host-pm-web/app/components/summary/SupportingInfo.vue
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/dashboard/[applicationId].vue
- strr-host-pm-web/app/pages/dashboard/index.vue
- strr-host-pm-web/app/stores/document.ts
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/app/utils/businessLicenseHelper.ts
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/unit/application-dashboard.spec.ts
*Issue:*
- https://github.com/bcgov/entity/issues/29592
**Both NOC & BL**
**Only BL**
**Only NOC**
> Host UI - Aug 1 BL Upload

- strr-base-web/app/interfaces/strr-api.ts
- strr-base-web/package.json
- strr-examiner-web/app/components/ApplicationInfoHeader.vue
- strr-examiner-web/app/components/AssignmentActions.vue
- strr-examiner-web/app/components/RegistrationInfoHeader.vue
- strr-examiner-web/app/composables/useExaminerActions.ts
- strr-examiner-web/app/composables/useExaminerRoute.ts
- strr-examiner-web/app/interfaces/registration-i.ts
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/dashboard.vue
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/mocks/mockedData.ts
- strr-examiner-web/tests/unit/components.spec.ts
- strr-examiner-web/tests/unit/dashboard.spec.ts
- strr-examiner-web/tests/unit/registration-details.spec.ts
- strr-examiner-web/tests/unit/use-examiner-route.spec.ts
- strr-host-pm-web/tests/mocks/mockedData.ts
*Issue:*
- https://github.com/bcgov/entity/issues/29235
- https://github.com/bcgov/entity/issues/28987
- https://github.com/bcgov/entity/issues/29968
- Depends on API changes in https://github.com/bcgov/STRR/pull/814
- Preview site will not work as expected as there base layer changes in this PR
> Examiner UI - Registration Assignee Impl & Separate out Decider from Reviewer

- strr-examiner-web/app/components/DecisionPanel.vue
- strr-examiner-web/app/composables/useExaminerDecision.ts
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/examine/[applicationId].vue
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/unit/host-application-details.spec.ts
*Issue:*
- bcgov/entity/issues/29893
- bcgov/entity/issues/29883
- Add base Decision component for Examiners
- Add Decision buttons
> Add Decision component for Examiners

- strr-examiner-web/app/components/ApprovalConditions.vue
- strr-examiner-web/app/components/DecisionPanel.vue
- strr-examiner-web/app/composables/useExaminerDecision.ts
- strr-examiner-web/app/layouts/examine.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/unit/registration-details.spec.ts
*Issue:*
- Custom Condition Component
- Dynamically update the Email to Competing Party text
- Add/delete multiple custom conditions
- Max 3 custom conditions
- Validation and error message
> Examiner Custom Condition

- strr-examiner-web/app/layouts/examine.vue
- strr-examiner-web/package.json
> Fix Examiner Decisions Flag

- strr-examiner-web/app/components/ActionButtons.vue
- strr-examiner-web/app/components/ApprovalConditions.vue
- strr-examiner-web/app/components/DecisionPanel.vue
- strr-examiner-web/app/composables/useExaminerDecision.ts
- strr-examiner-web/app/interfaces/conditions-of-approval.ts
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/app/pages/registration/[registrationId].vue
- strr-examiner-web/app/stores/examiner.ts
- strr-examiner-web/package.json
- strr-examiner-web/tests/unit/registration-details.spec.ts
*Issue:*
- bcgov/entity/issues/29905
- Submit Approval Conditions
> Submit Approval Conditions

- strr-host-pm-web/app/stores/hostApplication.ts
- strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/30415
- Update API payload for Renewals
> Update API payload for Renewals

- strr-examiner-web/app/components/ActionButtons.vue
- strr-examiner-web/app/components/Host/Expansion/FilingHistory.vue
- strr-examiner-web/app/locales/en-CA.ts
- strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/29296
- Remove Duplicated `Registration Created` Filing History Event
> Remove Duplicated History Event

- strr-host-pm-web/app/components/form/DefineYourRental/UnitAddress.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitDetails2.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/PrRequired.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/StrataHotelCategory.vue
- strr-host-pm-web/app/components/form/DefineYourRental/UnitSetupOptions.vue
- strr-host-pm-web/app/components/form/DefineYourRental/index.vue
- strr-host-pm-web/app/components/form/UnitAddress/Manual2.vue
- strr-host-pm-web/app/components/modal/info/PlatformRegNumHelp.vue
- strr-host-pm-web/app/composables/useHostApplicationFee.ts
- strr-host-pm-web/app/composables/useHostFeatureFlags.ts
- strr-host-pm-web/app/composables/useHostPmModals.ts
- strr-host-pm-web/app/enums/property-type.ts
- strr-host-pm-web/app/enums/rental-unit-setup-types.ts
- strr-host-pm-web/app/interfaces/host-api.ts
- strr-host-pm-web/app/interfaces/host-ui.ts
- strr-host-pm-web/app/interfaces/strata-hotel-categories.ts
- strr-host-pm-web/app/locales/en-CA.ts
- strr-host-pm-web/app/pages/application.vue
- strr-host-pm-web/app/stores/hostPermit.ts
- strr-host-pm-web/app/stores/hostProperty.ts
- strr-host-pm-web/app/stores/propertyRequirements.ts
- strr-host-pm-web/package.json
- strr-host-pm-web/tests/unit/application.spec.ts
*Issue:*
- bcgov/entity/issues/30645
- bcgov/entity/issues/30646
- bcgov/entity/issues/30644
- New form for Property Rental Setup
- PID field is moved within the form
- Updates to interfaces
- Feature Flag
- Validation
- Host Fee logic updates - display fees on Review step only
> New Form for Rental Unit Setup + Validation + Fees

- strr-host-pm-web/app/stores/document.ts
- strr-host-pm-web/package.json
*Issue:*
- Fix store dependencies issues - two stores call each other while initializing dependable props at the same time
> Fix store dependencies issue

- strr-api/pyproject.toml
- strr-api/src/strr_api/resources/registrations.py
- strr-api/tests/unit/resources/test_registrations.py
- strr-api/tests/unit/services/test_payment_service.py
*Issue:*
- https://github.com/bcgov/entity/issues/30955
> API - Renewal Draft Todo
