strr-web/components/bcros/form-section/property/Address.vue, strr-web/components/bcros/form-section/property/Form.vue, strr-web/stores/strr.ts
*Issue:* [20659](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20659) 
Fixes ability to add day past 31 for secondary birthday
Shows validation error when region outside of BC chosen for rental property address
=> Fixing Secondary Birthday & BC Lock

strr-web/components/bcros/form-section/contact-information/Form.vue, strr-web/composables/useRegistrations.ts, strr-web/stores/account.ts, strr-web/stores/strr.ts
Adding redirect logic to allow redirect to pay after account creation when:
- no files uploaded
- file upload fails
- all files uploaded
Fixing ToS acceptance loop issue
Fixing logic for prepopulating information after account select
=> Bugfix: Adding redirect on account creation with no documents

strr-api/pyproject.toml, strr-api/src/strr_api/models/application.py, strr-api/src/strr_api/resources/registrations.py, strr-api/src/strr_api/responses/AutoApprovalRecordResponse.py, strr-api/src/strr_api/services/approval_service.py, strr-api/tests/unit/common/test_run_version.py, strr-api/tests/unit/resources/test_registrations.py, strr-api/tests/unit/services/test_approval.py, strr-api/tests/unit/utils/mocks.py
*Issue:* https://github.com/bcgov/entity/issues/22348
- Auto-approve use application instead of registrations
- Update application status along with registration when applicable
- Currently relationship between `Application` and `Registrations` in the code is one-to-one. Whereas the RFC depicts this as many-to-one. Outlined in comments where and what changes will be needed to accommodate this.
=> Backend: Auto Approval - Use Application

strr-web/components/bcros/status-card/StatusCard.vue, strr-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/22485
- Remove `Renewal` button in Status Cards as the button functionality will be implemented later
=> Remove Renewal button in Status Cards

strr-api/src/strr_api/resources/__init__.py, strr-api/src/strr_api/resources/documents.py, strr-api/tests/postman/strr-api.postman_collection.json
*Issue:* https://github.com/bcgov/entity/issues/22914
=> Backend - Documents Endpoint Not Tied to Applications

strr-api/src/strr_api/resources/application.py, strr-api/src/strr_api/resources/registrations.py, strr-api/src/strr_api/services/document_service.py, strr-api/tests/postman/strr-api.postman_collection.json, strr-api/tests/unit/resources/test_registrations.py, strr-web/composables/useRegistrations.ts
*Issue:*
- https://github.com/bcgov/entity/issues/22961
- Commented out the registration document endpoints as they will not be used:
- `GET registrations/<registration_id>/documents`
- `GET registrations/<registration_id>/documents/<document_id>`
Needs to be cleanup in future
- Updated `registrations/<registration_id>/documents/<document_id>/file` to `registrations/<registration_id>/documents/<file_key>`
- Added postman test
=> Backend - Update Registrations Document Endpoints

strr-web/components/FeeWidget.vue, strr-web/components/bcros/stepper/StepperFooter.vue, strr-web/composables/useFees.ts, strr-web/layouts/wide.vue, strr-web/package.json, strr-web/pages/create-account-pre/[id].vue, strr-web/pages/create-account.vue, strr-web/pages/platform-application.vue, strr-web/tests/unit/components/fee-widget/FeeWidget.spec.ts, strr-web/tests/unit/pages/platform-application.spec.ts
*Issue:*
- bcgov/entity/issues/22764
- Add Fee Summary widget
- Integrate API calls for fees (small and large Platform fees) 
- Default is the Small Platform fee
- Update unit test
=> Add Fee Summary to Platform Application page

strr-web/components/bcros/form-section/principal-residence/Form.vue, strr-web/lang/en.json, strr-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/22520
Design:
With this PR:
=> UI - Document Upload - Align with Design

strr-web/components/bcros/form-section/property/Address.vue, strr-web/interfaces/account-i.ts, strr-web/lang/en.json, strr-web/nuxt.config.ts, strr-web/package.json, strr-web/stores/strr.ts, strr-web/tests/unit/utils/formStateToApi.spec.ts
*Issue:*
- bcgov/entity/issues/22519
- Remove Use Same Address Checkbox
- Show correct UI version in app footer
=> Remove Use Same Address Checkbox

strr-web/components/common/InfoModal.vue, strr-web/lang/en.json, strr-web/package.json, strr-web/pages/account-select.vue, strr-web/pages/create-account.vue, strr-web/pages/finalization.vue, strr-web/pages/registry-dashboard.vue
*Issue:*
- https://github.com/bcgov/entity/issues/22796
- https://github.com/bcgov/entity/issues/23083
[Design](https://www.figma.com/design/R9GF5wvwq2TrnbnsbhPfvV/STR-Application-Tickets?node-id=7406-9050&node-type=canvas&t=EcmDWvKdaghZhMlQ-0)
**FOIPPA**
**STRB Contact**
-  [x] A visible and easily accessible help button should be present throughout the application form
=> UI - FOIPPA Notice and STRB Contact Modal [Host Application and Dashboard]

strr-web/lang/en.json, strr-web/pages/application-status.vue, strr-web/pages/create-account.vue, strr-web/pages/registry-dashboard.vue
*Issue:*
- https://github.com/bcgov/entity/issues/23083
`Information Page` link redirects to https://www2.gov.bc.ca/gov/content/housing-tenancy/short-term-rentals/registry
=> UI - STRB Contact Modal [Application Status Page]

strr-web/composables/useChipFlavour.ts, strr-web/enums/application-status-e.ts, strr-web/lang/en.json, strr-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/22832
Includes a lang change suggested by Andy. Status collision fix between `PROVISIONALLY_APPROVED` [examiner] AND `PROVISIONAL_REVIEW` [host]
=> UI: Application Status Followup Fixes 

strr-web/components/bcros/status-card/StatusCard.vue, strr-web/composables/useDownloadCertificate.ts, strr-web/enums/registration-type-e.ts, strr-web/interfaces/application-i.ts, strr-web/interfaces/examiner-dashboard-row-i.ts, strr-web/lang/en.json, strr-web/package.json, strr-web/pages/registry-dashboard.vue, strr-web/tests/mocks/mockApplication.ts
*Issue:*
- https://github.com/bcgov/entity/issues/23532
Generic dashboard - Registration number link will open registration detail page. If certificate has been issued for that registration then a document icon will be displayed, clicking it will download certificate. Otherwise it will open application details [same as before with all rows except status]. 
Status Card - Download certificate button will only show if the certificate has been issued.
=> UI: Generic Dashboard Table for Examiners

strr-web/lang/en.json, strr-web/package.json, strr-web/pages/application-details/[id]/index.vue, strr-web/pages/registration-details/[id]/index.vue
*Issue:*
- bcgov/entity/issues/23551
- Add Business Lic Exp Date to Application and Registration Details pages
=> Add Business Lic Exp Date to Details pages

strr-platform-web/app/components/connect/Stepper.vue, strr-platform-web/app/components/form/platform/BusinessDetails.vue, strr-platform-web/app/components/form/platform/ContactInfo.vue, strr-platform-web/app/components/form/platform/Details.vue, strr-platform-web/app/components/form/platform/review/index.vue, strr-platform-web/app/composables/useStrrModals.ts, strr-platform-web/app/interfaces/step.ts, strr-platform-web/app/interfaces/validation.ts, strr-platform-web/app/pages/platform/application.vue, strr-platform-web/app/stores/platformApplication.ts, strr-platform-web/app/stores/platformBusiness.ts, strr-platform-web/app/stores/platformContact.ts, strr-platform-web/app/stores/platformDetails.ts, strr-platform-web/app/utils/formHelpers.ts, strr-platform-web/nuxt.config.ts
Refactor stepper component and handle validation for first step.
Main changes:
- all stepper logic is managed by the stepper and used in the parent through defineExpose and defineModel
- added a validationFn to the Step object so the stepper can validate itself if a validateFn is provided
- all ContactInfo forms in the step are validated onMounted if the isComplete prop = true, the form will still validate on input/blur/etc as the default UForm settings
- separated some of the form methods into the formHelpers util file
- a different validation function is defined in the contact info store which is then called in the application store on submit (this is different than the form validation function which is local to the form/step component, passing the form errors …
=> UI - Platform: Validation checkpoint

strr-platform-web/.env.example, strr-platform-web/playwright.config.ts, strr-platform-web/tests/e2e/platform.smoke.test.ts, strr-platform-web/tests/e2e/test-utils/auth-setup.ts
- playwright auth setup
- rewrite some tests to use getters
=> Platform - UI: auth setup for e2e tests

strr-web/components/bcros/form-section/principal-residence/Form.vue, strr-web/lang/en.json, strr-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/23014
Only allow .pdf supporting document upload.
=> Host UI - Only Allow PDF Document Upload

strr-base-web/app/app.config.ts, strr-base-web/app/components/connect/form/address/Index.vue, strr-base-web/app/components/connect/form/field/Group.vue, strr-base-web/app/components/connect/form/field/Index.vue, strr-base-web/app/composables/useCanadaPost.ts, strr-base-web/app/composables/useStrrApi.ts, strr-base-web/app/locales/en-CA.ts, strr-base-web/app/utils/connect-validation/index.ts, strr-platform-web/app/components/form/platform/BusinessDetails.vue, strr-platform-web/app/locales/en-CA.ts, strr-platform-web/app/stores/platformApplication.ts, strr-platform-web/package.json, strr-platform-web/pnpm-lock.yaml, strr-strata-web/app/components/form/BusinessDetails.vue, strr-strata-web/app/components/form/ReviewConfirm.vue, strr-strata-web/app/components/form/StrataDetails.vue, strr-strata-web/app/interfaces/strata-details.ts, strr-strata-web/app/locales/en-CA.ts, strr-strata-web/app/pages/application.vue, strr-strata-web/app/stores/strataApplication.ts, strr-strata-web/app/stores/strataDetails.ts, strr-strata-web/nuxt.config.ts, strr-strata-web/package.json, strr-strata-web/pnpm-lock.yaml
=> UI - strata hotel application

strr-base-web/app/locales/en-CA.ts, strr-platform-web/app/locales/en-CA.ts, strr-strata-web/app/app.config.ts, strr-strata-web/app/composables/useStrataModals.ts, strr-strata-web/app/locales/en-CA.ts, strr-strata-web/app/middleware/require-account.ts, strr-strata-web/app/pages/application.vue, strr-strata-web/app/pages/auth/account/choose-existing.vue, strr-strata-web/app/pages/strata-hotel/dashboard/[registrationId].vue, strr-strata-web/app/pages/strata-hotel/dashboard/index.vue, strr-strata-web/app/stores/strata.ts
*Issue:*
- bcgov/entity#24313
- strata dashboard list/table
- choose account page
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the strr2 license (Apache 2.0).
=> Strata - UI: Strata dashboard list

strr-base-web/app/composables/useNavigate.ts, strr-strata-web/app/pages/application.vue, strr-strata-web/app/stores/strataApplication.ts
~~Opening as draft for now as pay is being upgraded and I'm not able to test this quite yet~~
Payment is working now 
=> Strata - UI: cc payment redirect

strr-web/middleware/setupAuth.global.ts, strr-web/package.json, strr-web/stores/keycloak.ts
*Issue:*
When submitting a new Rental Application, the Success page was by-passed and user was navigated to Account Select page.
- Fix to allow users to navigate to Success Submission page
=> Allow to Navigate to Success Submission page

strr-base-web/app/components/connect/form/address/Index.vue, strr-base-web/app/components/connect/form/date/Input.vue, strr-base-web/app/components/connect/form/field/Group.vue, strr-base-web/app/components/connect/form/field/Index.vue, strr-base-web/app/locales/en-CA.ts, strr-base-web/app/utils/connect-validation/address.ts, strr-base-web/app/utils/connect-validation/index.ts, strr-base-web/app/utils/connect-validation/urls.ts, strr-base-web/app/utils/date.ts, strr-host-pm-web/app/components/form/PropertyDetails.vue, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/app/stores/hostProperty.ts
*Issue:*
- committing in progress work in step 1 before switch to new design
=> UI - new hosts step 1 updates

strr-host-pm-web/app/interfaces/host-api.ts, strr-host-pm-web/app/utils/host-formatting.ts
*Issue:*
- bcgov/entity/issues/24802
=> UI - hosts submit, tweaks

strr-base-web/app/locales/en-CA.ts, strr-base-web/app/middleware/auth.ts, strr-base-web/app/pages/auth/login.vue, strr-host-pm-web/nuxt.config.ts, strr-host-pm-web/package.json, strr-platform-web/package.json, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24560
- prevent specific idps from accessing app
=> Invalid idp middleware

strr-base-web/app/app.config.ts, strr-base-web/app/locales/en-CA.ts, strr-base-web/app/pages/auth/login.vue, strr-base-web/app/types/strr-base-app-config.d.ts, strr-host-pm-web/app/app.config.ts, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/app/middleware/choose-account-page.ts, strr-host-pm-web/app/middleware/create-account-page.ts, strr-host-pm-web/app/pages/auth/account/choose-existing.vue, strr-host-pm-web/app/pages/auth/account/create-new.vue, strr-host-pm-web/nuxt.config.ts, strr-host-pm-web/package.json, strr-platform-web/app/app.config.ts, strr-platform-web/package.json, strr-strata-web/app/app.config.ts, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24904
- bcgov/entity/issues/24898
- bcgov/entity/issues/24903
- add subtext option to login page login buttons
- update login page styling & button labels
- remove login menu, create account button and locale select from header in all apps
- allow bceid in Hosts
- middleware to prevent bceid user from accessing create-account page in hosts
- create account button on 'select existing account' page in hosts goes to external account creation instead of strr create account page
Hosts login screen:
Platform login screen: 
Strata login screen:
=> Host/Strata/Platform - UI: Login stuff

strr-base-web/.eslintrc, strr-base-web/app/components/connect/form/address/Index.vue, strr-base-web/app/components/connect/form/field/Group.vue, strr-base-web/app/components/connect/form/field/Index.vue, strr-base-web/app/components/connect/form/phoneNumber/Index.vue, strr-base-web/app/components/form/common/Contact.vue, strr-host-pm-web/app/components/form/UnitAddress/AutoComplete.vue, strr-host-pm-web/app/components/form/UnitAddress/Manual.vue, strr-host-pm-web/package.json, strr-platform-web/package.json, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24207
- set maxlength property for all inputs
- fix linter
=> All - UI: set max length for all inputs

strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/app/pages/dashboard/index.vue, strr-host-pm-web/package.json, strr-strata-web/app/locales/en-CA.ts, strr-strata-web/app/pages/strata-hotel/dashboard/index.vue, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24499
- add descriptive aria labels for the 'View' button in the dashboard table
Hosts:
Strata: 
=> Strata/Hosts - UI: View btn

strr-base-web/app/app.config.ts, strr-base-web/app/composables/useStrrModals.ts, strr-base-web/package.json, strr-base-web/pnpm-lock.yaml, strr-host-pm-web/package.json, strr-host-pm-web/pnpm-lock.yaml, strr-platform-web/app/pages/platform/application.vue, strr-platform-web/app/pages/platform/dashboard.vue, strr-platform-web/app/utils/account-change.ts, strr-platform-web/nuxt.config.ts, strr-platform-web/package.json, strr-platform-web/pnpm-lock.yaml, strr-strata-web/package.json, strr-strata-web/pnpm-lock.yaml
*Issue:*
- bcgov/entity/issues/25029
- bump core layer version to use account change route meta
- fix radio group styling
=> All - UI: radio group position

strr-examiner-web/app/components/ApplicationDetails.vue, strr-examiner-web/app/components/ApplicationDetailsSection.vue, strr-examiner-web/app/components/RegistrationDetails.vue, strr-examiner-web/app/layouts/examiner.vue, strr-examiner-web/app/pages/dashboard/[applicationId].vue, strr-examiner-web/app/pages/dashboard/index.vue, strr-examiner-web/app/store/examiner.ts, strr-examiner-web/nuxt.config.ts, strr-examiner-web/package.json, strr-examiner-web/pnpm-lock.yaml
*Issue:*
- Updates to Examiner Dashboard based on wip designs
=> Updates to Examiner Dashboard

strr-base-web/app/components/form/ContactInfo.vue, strr-base-web/app/locales/en-CA.ts, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/app/stores/document.ts, strr-host-pm-web/package.json, strr-strata-web/app/components/document/list/Item.vue, strr-strata-web/app/components/document/list/index.vue, strr-strata-web/app/components/document/upload/Button.vue, strr-strata-web/app/components/document/upload/Select.vue, strr-strata-web/app/components/form/BusinessDetails.vue, strr-strata-web/app/components/form/ReviewConfirm.vue, strr-strata-web/app/components/form/StrataDetails.vue, strr-strata-web/app/enums/document-upload-type.ts, strr-strata-web/app/interfaces/strata-api.ts, strr-strata-web/app/interfaces/ui-document.ts, strr-strata-web/app/locales/en-CA.ts, strr-strata-web/app/pages/application.vue, strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue, strr-strata-web/app/stores/document.ts, strr-strata-web/app/stores/strata.ts, strr-strata-web/app/stores/strataApplication.ts, strr-strata-web/nuxt.config.ts, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25006
- 
=> Strata - UI: Strata doc upload

strr-host-pm-web/app/pages/dashboard/[applicationId].vue, strr-host-pm-web/package.json, strr-strata-web/app/components/form/StrataDetails.vue, strr-strata-web/app/locales/en-CA.ts, strr-strata-web/app/pages/strata-hotel/dashboard/[applicationId].vue, strr-strata-web/app/stores/document.ts, strr-strata-web/nuxt.config.ts, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/25122
- make document upload in strata form optional
- navigate from /dashboard/:id  -->  /dashboard when user changes accounts in strata and host
=> Strata - UI: document upload optional

strr-base-web/app/app.config.ts, strr-base-web/app/components/connect/fee/Widget.vue, strr-base-web/app/components/connect/form/address/Display.vue, strr-base-web/app/components/connect/form/field/Group.vue, strr-base-web/app/types/strr-base-app-config.d.ts, strr-base-web/app/utils/connect-address.ts, strr-base-web/nuxt.config.ts, strr-host-pm-web/.env.example, strr-host-pm-web/app/app.config.ts, strr-host-pm-web/app/components/form/AddDocuments/index.vue, strr-host-pm-web/app/components/form/AddOwners/Index.vue, strr-host-pm-web/app/components/form/DefineYourRental/UnitAddress.vue, strr-host-pm-web/app/components/form/DefineYourRental/UnitDetails.vue, strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/StrProhibited.vue, strr-host-pm-web/app/components/form/DefineYourRental/UnitRequirements/StraaExempt.vue, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/devops/vaults.env, strr-host-pm-web/nuxt.config.ts, strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25183
- update text per revision figma
=> Host text update

strr-base-web/app/composables/useStrrApi.ts, strr-base-web/app/composables/useStrrBasePermit.ts, strr-base-web/app/composables/useStrrBasePermitList.ts, strr-base-web/app/interfaces/strr-api.ts, strr-examiner-web/app/layouts/examiner.vue, strr-examiner-web/app/pages/dashboard.vue, strr-examiner-web/app/pages/examine/[applicationId].vue, strr-examiner-web/app/store/examiner.ts, strr-examiner-web/package.json, strr-host-pm-web/app/pages/dashboard/index.vue, strr-host-pm-web/app/stores/hostPermit.ts, strr-host-pm-web/package.json, strr-strata-web/app/pages/strata-hotel/dashboard/index.vue, strr-strata-web/app/stores/strata.ts, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/24951
- bcgov/entity/issues/25210
- examination changes are just first pass / will probably be changed with updated design + reqs
- confirmed the filtering updates and other tweaks in host/strata with scott
- pagination only shows when the result set is more than 50:
=> UI - hosts,strata,examiner applications table updates

strr-base-web/app/components/connect/checklist/Validated.vue, strr-host-pm-web/app/components/form/AddDocuments/index.vue, strr-host-pm-web/app/components/form/AddOwners/Index.vue, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/25313
- bcgov/entity/issues/25314
- move checklist inside doc upload card
- add text above bl input
- update label for number of rooms
- fix icon sizing on mobile
=> Host - UI: item placement

strr-web/package.json, strr-web/pages/registration-details/[id]/index.vue
*Issue:*
Registration Details page issues with PR info
- Fix to show only one Principal Res requirement in Registration page
=> Fix Registration Details page. Show PR if available

strr-base-web/app/composables/useStrrApi.ts, strr-examiner-web/app/components/Host/Expansion/Owners.vue, strr-examiner-web/app/interfaces/application-error.ts, strr-examiner-web/app/pages/dashboard.vue, strr-examiner-web/app/pages/examine/[applicationId].vue, strr-examiner-web/app/stores/examiner.ts, strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/25360
- fix page render when error issue
- create initial error state (needs further design)
- fix typing
https://github.com/user-attachments/assets/5cf6a486-9ace-497a-b643-3b1bbfe828a9
=> Create interim error state, fix typing

strr-api/pyproject.toml, strr-api/src/strr_api/models/application.py, strr-api/src/strr_api/models/dataclass.py, strr-api/src/strr_api/resources/application.py, strr-api/tests/postman/strr-api.postman_collection.json, strr-host-pm-web/tests/e2e/test-utils/page-helpers.ts
*Issue:*
- https://github.com/bcgov/entity/issues/26041
Addresses @dimak1 comment:
One item is missing from the list - the logic for "get next" application that we did not finalized.
Currently, if examiner clicks 'Examine` tab or Approve/Refuse buttons, they are navigated to next application details page. The next application by default is first Host application under Full Review returned by API.
=> API - List Applications OrderBy

strr-base-web/app/interfaces/strr-api.ts, strr-base-web/app/utils/date.ts, strr-examiner-web/app/components/ApplicationInfoHeader.vue, strr-examiner-web/app/components/ComposeNoc.vue, strr-examiner-web/app/components/RegistrationInfoHeader.vue, strr-examiner-web/app/composables/useExaminerActions.ts, strr-examiner-web/app/composables/useExaminerRoute.ts, strr-examiner-web/app/enums/actions.ts, strr-examiner-web/app/locales/en-CA.ts, strr-examiner-web/app/pages/dashboard.vue, strr-examiner-web/app/pages/examine/[applicationId].vue, strr-examiner-web/app/pages/registration/[registrationId].vue, strr-examiner-web/app/stores/examiner.ts, strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26241
- Examiner NOC UI changes
- Removed suspend action for registrations (per feedback from Andy)
- RegistrationInfoHeader - fixed `Submitted`, added missing | between registration & expiry date
- RegistrationInfoHeader & ApplicationInfoHeader - lowercase am and pm
- Deviation from design
- Width of NOC component to be same as section above (checked with Andy)
- Refuse/reject is an acceptable examiner action for `FULL_REVIEW` status (discussed with Lekshmi)
=> UI - Examiner NOC

strr-examiner-web/app/components/Host/SubHeader.vue, strr-examiner-web/app/components/Host/SupportingInfo.vue, strr-examiner-web/app/components/Strata/SupportingInfo.vue, strr-examiner-web/app/components/SupportingDocuments.vue, strr-examiner-web/app/interfaces/supporting-documents.ts, strr-examiner-web/app/stores/examiner.ts, strr-examiner-web/package.json, strr-examiner-web/tests/unit/components.spec.ts, strr-examiner-web/tests/unit/host-application-details.spec.ts
*Issue:*
- bcgov/entity/issues/26234
- Refactor SupportingDocuments component to support existing and NOC documents, for Host and Strata
- Main requirement: Show NOC documents (with badges) separately on the new line below the initial application documents
- Use a config to display different documents based on requirements
- Add unit tests
=> Refactor Supporting Documents for Host and Strata

strr-base-web/app/utils/todoItems.ts, strr-base-web/package.json
*Issue:*
- bcgov/entity/issues/26622
- Rework scroll to Supporting Info section in To Do for Pending NOC
=> Fix scroll in To Do for Pending NOC

strr-examiner-web/app/components/Host/Expansion/Owners.vue, strr-examiner-web/app/locales/en-CA.ts, strr-examiner-web/package.json, strr-host-pm-web/app/components/form/AddOwners/Index.vue, strr-host-pm-web/app/components/form/AddOwners/input/Person.vue, strr-host-pm-web/app/components/summary/Owners.vue, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/app/stores/hostOwner.ts, strr-host-pm-web/app/utils/host-permit-dash-helpers.ts, strr-host-pm-web/package.json, strr-host-pm-web/tests/mocks/mockedData.ts, strr-host-pm-web/tests/unit/application-dashboard.spec.ts
*Issue:*
- bcgov/entity/issues/26232
- Make CRA Tax Number Optional for Hosts
- Add unit test
=> Make CRA Tax Number Optional

strr-examiner-web/app/components/Host/SubHeader.vue, strr-examiner-web/app/components/Table/Header/DateRange.vue, strr-examiner-web/app/components/Table/Header/Input.vue, strr-examiner-web/app/components/Table/Header/Select.vue, strr-examiner-web/app/locales/en-CA.ts, strr-examiner-web/app/pages/dashboard.vue, strr-examiner-web/app/stores/examiner.ts, strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/26229
- https://github.com/bcgov/entity/issues/26675
- https://github.com/bcgov/entity/issues/26677
- https://github.com/bcgov/STRR/pull/636 needs to be merged before testing this as it relies on the backend changes
- Addresses previously noted UXA feedback and styling updates
- Current state
=> UI - Status and Type - Support Multiple Filters and more

strr-api/pyproject.toml, strr-api/src/strr_api/models/application.py, strr-api/tests/unit/resources/test_registration_applications.py
*Issue:*
- https://github.com/bcgov/entity/issues/26657
`NO_REQ` (Scenario 6) means not having PR or BL requirements
=> Examiner API - Requirements Filter - Host NO_REQ Criteria Update

strr-api/src/strr_api/services/application_service.py, strr-api/tests/unit/resources/test_registration_applications.py
*Issue:*
- https://github.com/bcgov/entity/issues/26347
Based on clarified requirement from @andyyanggov. Assign and Unassign need to allowed for other application statuses and not just `FULL_REVIEW & PROVISIONAL_REVIEW`.
https://github.com/bcgov/STRR/pull/669#issuecomment-2787723952
=> API - Assign & Unassign - Allow on all statuses

strr-base-web/app/locales/en-CA.ts, strr-base-web/package.json, strr-host-pm-web/app/components/form/AddDocuments/index.vue, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/package.json, strr-strata-web/app/components/form/StrataDetails.vue, strr-strata-web/app/locales/en-CA.ts, strr-strata-web/package.json
*Issue:*
- bcgov/entity/issues/27134
- Allow Hosts to upload images (jpeg, jpg) when adding documents in Step 3 of the Host and Strata applications
- Update text
=> Allow Image Upload for Hosts

strr-api/pyproject.toml, strr-api/src/strr_api/models/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/27356
`Application.Status.PROVISIONAL_REVIEW_NOC_PENDING: "Notice of Consideration - Submissions Open",
Application.Status.PROVISIONAL_REVIEW_NOC_EXPIRED: "Notice of Consideration - Submissions Closed",`
Will be added when this is merged with main
=> API Hotfix - Update NOC Status Labels

strr-api/src/strr_api/models/application.py
*Issue:*
- https://github.com/bcgov/entity/issues/27356
```
Application.Status.PROVISIONAL_REVIEW_NOC_PENDING: "Notice of Consideration",
Application.Status.PROVISIONAL_REVIEW_NOC_EXPIRED: "Pending Review",
Application.Status.PROVISIONAL_REVIEW_NOC_PENDING: "NOC - Pending",
Application.Status.PROVISIONAL_REVIEW_NOC_EXPIRED: "NOC - Expired",
```
Will be added when this is merged with main
=> API Hotfix - Update NOC Status Labels - Changed Requirements

strr-api/src/strr_api/models/application.py, strr-api/tests/unit/resources/test_registration_applications.py
- https://github.com/bcgov/STRR/pull/710
=> Sync Hotfix 23756 to Main 

strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/app/stores/document.ts, strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/27638
- Add Farmland PR Requirement to ask for Property Assessment Notice to be uploaded
=> Add Farmland PR Requirement

strr-base-web/app/composables/useStrrBasePermit.ts, strr-base-web/app/locales/en-CA.ts, strr-base-web/app/utils/accountDashHelpers.ts, strr-base-web/app/utils/todoItems.ts, strr-base-web/package.json, strr-examiner-web/app/locales/en-CA.ts, strr-host-pm-web/app/components/summary/SupportingInfo.vue, strr-host-pm-web/app/pages/dashboard/[applicationId].vue, strr-host-pm-web/app/pages/dashboard/index.vue, strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/28432
- Host Dashboard should show and Application and not Registration
- Host should be able to upload additional documents (as per usual NOC flow)
- To Do item for Hosts
=> Host Application view with Provisional NOC

strr-base-web/app/components/connect/form/address/DisplayItem.vue, strr-base-web/package.json, strr-host-pm-web/app/components/summary/Property.vue, strr-host-pm-web/app/locales/en-CA.ts, strr-host-pm-web/package.json
=> UI - Host Dashboard Change - Sync Feature w/ Release Branch

strr-examiner-web/app/components/ApplicationInfoHeader.vue, strr-examiner-web/app/locales/en-CA.ts, strr-examiner-web/package.json
*Issue:*
- Add Declined Date for Declined Applications
- Use `decisionDate` for the date (?)
=> Add Application Declined Date

strr-examiner-web/app/utils/format-helper.ts, strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/28813
- Add dash after Unit Number in Examiner Details View
=> Add dash after Unit Number in Examiner Details View

strr-host-pm-web/app/pages/application.vue, strr-host-pm-web/package.json
*Issue:*
- bcgov/entity/issues/26265
- Fees weren't reflecting properly in the UI when switching Type of Space and Rental Unit Set-up
- Fix by creating a shallow copy of the fees, instead of copying by reference 
=> Fix Fee Widget Recalculation

strr-examiner-web/app/components/Host/SubHeader.vue, strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/28965
- Disable Edit Address for Cancelled Registrations
=> Disable Edit Address for Registrations

strr-host-pm-web/app/components/summary/SupportingInfo.vue, strr-host-pm-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/29902
Tested in DEV:
- H307931455 , 36458020593230
- H270872610, 48948108028967
Add document to registration flow will only be triggered if either there is a registration NOC or BL jurisdiction condition is met. For applications with `PROVISIONAL_REVIEW_NOC_PENDING` the documents will be uploaded to application instead of registration (see Arlen comment below).
Because of NOC status flag check in registration document upload endpoint I encountered the following issue:
This is what the final requirements from Arlen were:
=> Host UI Fix - `PROVISIONAL_REVIEW_NOC_PENDING` unable to upload documents

strr-base-web/app/interfaces/strr-api.ts, strr-base-web/app/interfaces/ui-document.ts, strr-examiner-web/app/components/Host/SupportingInfo.vue, strr-examiner-web/app/components/Strata/SupportingInfo.vue, strr-examiner-web/app/components/SupportingDocuments.vue, strr-examiner-web/app/interfaces/supporting-documents.ts, strr-examiner-web/package.json
*Issue:*
- https://github.com/bcgov/entity/issues/29671
Badges showing for registration NOC & BL
Application
=> Examiner UI - Registration Details - Date Badge for NOC & BL Upload Docs

strr-examiner-web/app/components/ActionButtons.vue, strr-examiner-web/package.json
*Issue:*
- bcgov/entity/issues/30776
- Fix Action Button logic for Set Aside. Make conditions more clear.
=> Fix Action Button logic for Set Aside Registrations
